"""부산 큐레이션 시드 (8곳)."""
from .helpers import unsplash

BUSAN_SEED: list[tuple[str, dict]] = [
    ("seed:busan:haeundae-beach", {
        "country": "KR", "city": "busan", "region": "해운대",
        "name": "해운대 해수욕장", "name_en": "Haeundae Beach",
        "address": "부산 해운대구 우동",
        "latitude": 35.1587, "longitude": 129.1604,
        "category": "nature", "vibe_tags": ["활기", "감성", "야경"],
        "description": "부산을 상징하는 해변. 여름 해변, 겨울 일출.",
        "cover_image": unsplash("photo-1505228395891-9a51e7e86bf6"),
        "instagram_hashtag": "#해운대", "rating": 4.5, "review_count": 28000,
        "popularity_score": 95.0, "safety_score": 5,
    }),
    ("seed:busan:gamcheon-village", {
        "country": "KR", "city": "busan", "region": "사하",
        "name": "감천문화마을", "name_en": "Gamcheon Culture Village",
        "address": "부산 사하구 감내2로 203",
        "latitude": 35.0974, "longitude": 129.0107,
        "category": "photospot", "vibe_tags": ["레트로", "감성", "인스타"],
        "description": "산비탈 컬러풀 마을. 부산의 산토리니.",
        "cover_image": unsplash("photo-1538485399081-7c8970e76d2c"),
        "instagram_hashtag": "#감천문화마을", "rating": 4.4, "review_count": 19000,
        "popularity_score": 91.0, "women_friendly": True,
    }),
    ("seed:busan:huinnyeoul-village", {
        "country": "KR", "city": "busan", "region": "영도",
        "name": "흰여울문화마을", "name_en": "Huinnyeoul Culture Village",
        "address": "부산 영도구 영선동4가",
        "latitude": 35.0789, "longitude": 129.0537,
        "category": "photospot", "vibe_tags": ["감성", "한적", "분위기"],
        "description": "바다 절벽 위 골목 마을. 영도 산책 코스.",
        "cover_image": unsplash("photo-1554188248-986adbb73be4"),
        "instagram_hashtag": "#흰여울문화마을", "rating": 4.5, "review_count": 4900,
        "popularity_score": 82.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:busan:gwangalli-beach", {
        "country": "KR", "city": "busan", "region": "수영",
        "name": "광안리 해수욕장", "name_en": "Gwangalli Beach",
        "address": "부산 수영구 광안해변로",
        "latitude": 35.1531, "longitude": 129.1188,
        "category": "photospot", "vibe_tags": ["야경", "활기", "감성"],
        "description": "광안대교 야경과 드론쇼 명소.",
        "cover_image": unsplash("photo-1493976040374-85c8e12f0c0e"),
        "instagram_hashtag": "#광안리", "rating": 4.6, "review_count": 21000,
        "popularity_score": 93.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:busan:f1963", {
        "country": "KR", "city": "busan", "region": "수영",
        "name": "F1963", "name_en": "F1963",
        "address": "부산 수영구 망미배산로 17-7",
        "latitude": 35.1789, "longitude": 129.1167,
        "category": "cafe", "vibe_tags": ["빈티지", "모던", "감성"],
        "description": "철공장을 개조한 복합 문화 공간. 카페·서점·전시.",
        "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
        "instagram_hashtag": "#f1963", "rating": 4.5, "review_count": 5800,
        "price_level": 2, "popularity_score": 78.0, "women_friendly": True,
    }),
    ("seed:busan:momos-coffee", {
        "country": "KR", "city": "busan", "region": "영도",
        "name": "모모스커피 영도 로스터리", "name_en": "Momos Coffee Yeongdo",
        "address": "부산 영도구 봉래나루로 109",
        "latitude": 35.0930, "longitude": 129.0480,
        "category": "cafe", "vibe_tags": ["모던", "감성"],
        "description": "월드 바리스타 챔피언이 운영하는 로스터리 카페.",
        "cover_image": unsplash("photo-1495474472287-4d71bcdd2085"),
        "instagram_hashtag": "#모모스커피", "rating": 4.6, "review_count": 4200,
        "price_level": 2, "popularity_score": 81.0, "women_friendly": True,
    }),
    ("seed:busan:jagalchi-market", {
        "country": "KR", "city": "busan", "region": "중구",
        "name": "자갈치 시장", "name_en": "Jagalchi Fish Market",
        "address": "부산 중구 자갈치해안로 52",
        "latitude": 35.0966, "longitude": 129.0306,
        "category": "shopping", "vibe_tags": ["레트로", "활기"],
        "description": "한국 최대 수산시장. 회·해산물 즉석 식사.",
        "cover_image": unsplash("photo-1604754742629-3e0498a8f4ee"),
        "instagram_hashtag": "#자갈치시장", "rating": 4.2, "review_count": 11000,
        "price_level": 2, "popularity_score": 80.0,
    }),
    ("seed:busan:millak-raw-fish", {
        "country": "KR", "city": "busan", "region": "수영",
        "name": "민락회타운", "name_en": "Millak Raw Fish Town",
        "address": "부산 수영구 광안해변로 309",
        "latitude": 35.1543, "longitude": 129.1267,
        "category": "restaurant", "vibe_tags": ["활기", "분위기"],
        "description": "광안대교 야경 보며 회 한 접시.",
        "cover_image": unsplash("photo-1579871494447-9811cf80d66c"),
        "instagram_hashtag": "#민락회타운", "rating": 4.2, "review_count": 3400,
        "price_level": 3, "popularity_score": 73.0,
    }),
]
