"""유럽 도시 큐레이션 시드 — 파리·런던·암스테르담·바르셀로나·로마·프라하."""

from .helpers import unsplash

# ─── 파리 (8곳) ──────────────────────────────────────────────────────────────
PARIS_SEED: list[tuple[str, dict]] = [
    (
        "seed:paris:eiffel-tower",
        {
            "country": "FR",
            "city": "paris",
            "region": "7구",
            "name": "에펠탑",
            "name_en": "Eiffel Tower",
            "address": "Champ de Mars, 5 Avenue Anatole France, 75007 Paris",
            "latitude": 48.8584,
            "longitude": 2.2945,
            "category": "photospot",
            "vibe_tags": ["역사", "야간", "감성"],
            "description": "파리 상징. 매시간 정각 야간 반짝이는 조명쇼 5분. 전망대 3층까지 오픈.",
            "cover_image": unsplash("photo-1499856871958-5b9627545d1a"),
            "rating": 4.7,
            "review_count": 85000,
            "price_level": 2,
            "popularity_score": 99.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:paris:louvre-museum",
        {
            "country": "FR",
            "city": "paris",
            "region": "1구",
            "name": "루브르 박물관",
            "name_en": "Louvre Museum",
            "address": "Rue de Rivoli, 75001 Paris",
            "latitude": 48.8606,
            "longitude": 2.3376,
            "category": "culture",
            "vibe_tags": ["예술", "역사", "모던"],
            "description": "세계 최대 미술관. 모나리자·밀로의 비너스·사모트라케의 니케. 예약 필수.",
            "cover_image": unsplash("photo-1548449112-96a38a643324"),
            "rating": 4.7,
            "review_count": 72000,
            "price_level": 2,
            "popularity_score": 98.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:paris:montmartre",
        {
            "country": "FR",
            "city": "paris",
            "region": "18구",
            "name": "몽마르트르 언덕 & 사크레쾨르",
            "name_en": "Montmartre & Sacré-Cœur",
            "address": "35 Rue du Chevalier de la Barre, 75018 Paris",
            "latitude": 48.8867,
            "longitude": 2.3431,
            "category": "culture",
            "vibe_tags": ["감성", "예술", "역사"],
            "description": "파리 예술가의 거리. 흰 돔 사원 사크레쾨르에서 파리 전경 360도.",
            "cover_image": unsplash("photo-1499856871958-5b9627545d1a"),
            "rating": 4.6,
            "review_count": 48000,
            "price_level": 1,
            "popularity_score": 95.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:paris:le-marais",
        {
            "country": "FR",
            "city": "paris",
            "region": "3·4구",
            "name": "르 마레 지구",
            "name_en": "Le Marais",
            "address": "Le Marais, 75003/75004 Paris",
            "latitude": 48.8572,
            "longitude": 2.3600,
            "category": "shopping",
            "vibe_tags": ["트렌디", "감성", "활기"],
            "description": "유대인 지구+LGBT 성지+빈티지숍+팔라펠 거리. 피카소 미술관 포함.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.5,
            "review_count": 28000,
            "price_level": 2,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:paris:cafe-de-flore",
        {
            "country": "FR",
            "city": "paris",
            "region": "6구",
            "name": "카페 드 플로르",
            "name_en": "Café de Flore",
            "address": "172 Boulevard Saint-Germain, 75006 Paris",
            "latitude": 48.8541,
            "longitude": 2.3335,
            "category": "cafe",
            "vibe_tags": ["고급", "감성", "빈티지"],
            "description": "1887년 개업 파리 문화 아이콘. 사르트르·보부아르·피카소가 단골이었던 카페.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "rating": 4.3,
            "review_count": 18000,
            "price_level": 3,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:paris:versailles",
        {
            "country": "FR",
            "city": "paris",
            "region": "베르사유",
            "name": "베르사유 궁전",
            "name_en": "Palace of Versailles",
            "address": "Place d'Armes, 78000 Versailles",
            "latitude": 48.8048,
            "longitude": 2.1204,
            "category": "culture",
            "vibe_tags": ["역사", "고급", "자연"],
            "description": "루이 14세 태양왕의 궁전. 거울의 방·대정원 분수쇼. 파리에서 RER 40분.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.7,
            "review_count": 52000,
            "price_level": 3,
            "popularity_score": 96.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:paris:seine-river-cruise",
        {
            "country": "FR",
            "city": "paris",
            "region": "1구",
            "name": "센강 유람선 (바토 무슈)",
            "name_en": "Seine River Cruise",
            "address": "Port de la Conférence, 75008 Paris",
            "latitude": 48.8638,
            "longitude": 2.3116,
            "category": "nature",
            "vibe_tags": ["야간", "감성", "힐링"],
            "description": "파리 명소를 강에서 감상. 야간 에펠탑 조명쇼와 함께하는 로맨틱 크루즈.",
            "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
            "rating": 4.4,
            "review_count": 22000,
            "price_level": 2,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:paris:musee-dorsay",
        {
            "country": "FR",
            "city": "paris",
            "region": "7구",
            "name": "오르세 미술관",
            "name_en": "Musée d'Orsay",
            "address": "1 Rue de la Légion d'Honneur, 75007 Paris",
            "latitude": 48.8600,
            "longitude": 2.3266,
            "category": "culture",
            "vibe_tags": ["예술", "조용", "역사"],
            "description": "인상파 최대 컬렉션. 모네·르누아르·반 고흐 원작 집결. 기차역 개조 건물.",
            "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
            "rating": 4.7,
            "review_count": 38000,
            "price_level": 2,
            "popularity_score": 94.0,
            "women_friendly": True,
        },
    ),
]

# ─── 런던 (7곳) ──────────────────────────────────────────────────────────────
LONDON_SEED: list[tuple[str, dict]] = [
    (
        "seed:london:tower-bridge",
        {
            "country": "GB",
            "city": "london",
            "region": "타워 햄릿",
            "name": "타워 브리지",
            "name_en": "Tower Bridge",
            "address": "Tower Bridge Rd, London SE1 2UP",
            "latitude": 51.5055,
            "longitude": -0.0754,
            "category": "photospot",
            "vibe_tags": ["역사", "야간", "포토"],
            "description": "런던 상징 빅토리아 시대 도개교. 유리 바닥 전망대. 야경 명소.",
            "cover_image": unsplash("photo-1513635269975-59663e0ac1ad"),
            "rating": 4.6,
            "review_count": 58000,
            "price_level": 2,
            "popularity_score": 97.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:london:british-museum",
        {
            "country": "GB",
            "city": "london",
            "region": "블룸즈버리",
            "name": "대영박물관",
            "name_en": "British Museum",
            "address": "Great Russell St, London WC1B 3DG",
            "latitude": 51.5194,
            "longitude": -0.1270,
            "category": "culture",
            "vibe_tags": ["역사", "예술", "조용"],
            "description": "로제타석·엘긴 마블·이집트 미라 등 800만점 세계 유물. 무료 입장.",
            "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
            "rating": 4.7,
            "review_count": 65000,
            "price_level": 1,
            "popularity_score": 97.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:london:notting-hill",
        {
            "country": "GB",
            "city": "london",
            "region": "켄싱턴",
            "name": "노팅힐 & 포토벨로 마켓",
            "name_en": "Notting Hill & Portobello Market",
            "address": "Portobello Rd, Notting Hill, London W11",
            "latitude": 51.5149,
            "longitude": -0.2031,
            "category": "shopping",
            "vibe_tags": ["감성", "빈티지", "활기"],
            "description": "알록달록 파스텔 타운하우스. 영화 배경. 토요일 포토벨로 골동품 마켓.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.4,
            "review_count": 21000,
            "price_level": 2,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:london:borough-market",
        {
            "country": "GB",
            "city": "london",
            "region": "서더크",
            "name": "버로우 마켓",
            "name_en": "Borough Market",
            "address": "8 Southwark St, London SE1 1TL",
            "latitude": 51.5055,
            "longitude": -0.0910,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌", "활기"],
            "description": "런던 최대 식품 마켓. 수제 치즈·신선 굴·스트리트 푸드. 목~토 운영.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.5,
            "review_count": 29000,
            "price_level": 2,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:london:covent-garden",
        {
            "country": "GB",
            "city": "london",
            "region": "코벤트가든",
            "name": "코벤트 가든",
            "name_en": "Covent Garden",
            "address": "Covent Garden, London WC2E 8BE",
            "latitude": 51.5117,
            "longitude": -0.1228,
            "category": "shopping",
            "vibe_tags": ["활기", "트렌디", "예술"],
            "description": "야외 공연·고급 부티크·레스토랑 집결. 퍼포머 버스킹 365일.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.4,
            "review_count": 31000,
            "price_level": 2,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:london:hyde-park",
        {
            "country": "GB",
            "city": "london",
            "region": "켄싱턴",
            "name": "하이드 파크",
            "name_en": "Hyde Park",
            "address": "Hyde Park, London W2 2UH",
            "latitude": 51.5073,
            "longitude": -0.1657,
            "category": "nature",
            "vibe_tags": ["힐링", "자연", "활기"],
            "description": "142헥타르 왕립공원. 서펜타인 갤러리·롤러블레이딩·스피커스 코너.",
            "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
            "rating": 4.5,
            "review_count": 35000,
            "price_level": 1,
            "popularity_score": 91.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:london:sky-garden",
        {
            "country": "GB",
            "city": "london",
            "region": "시티오브런던",
            "name": "스카이 가든",
            "name_en": "Sky Garden",
            "address": "1 Sky Garden Walk, London EC3M 8AF",
            "latitude": 51.5113,
            "longitude": -0.0832,
            "category": "photospot",
            "vibe_tags": ["뷰포인트", "야간", "자연"],
            "description": "'워키토키' 빌딩 35층 무료 전망 정원. 템스강·타워브리지 조망 예약 필수.",
            "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
            "rating": 4.5,
            "review_count": 22000,
            "price_level": 1,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
]

# ─── 암스테르담 (6곳) ─────────────────────────────────────────────────────────
AMSTERDAM_SEED: list[tuple[str, dict]] = [
    (
        "seed:amsterdam:rijksmuseum",
        {
            "country": "NL",
            "city": "amsterdam",
            "region": "오우드 자위트",
            "name": "국립박물관 (레이크스무제움)",
            "name_en": "Rijksmuseum",
            "address": "Museumstraat 1, 1071 XX Amsterdam",
            "latitude": 52.3600,
            "longitude": 4.8852,
            "category": "culture",
            "vibe_tags": ["예술", "역사", "조용"],
            "description": "렘브란트·베르메르 황금시대 걸작. '야경' 원작 감상. 예약 필수.",
            "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
            "rating": 4.8,
            "review_count": 45000,
            "price_level": 2,
            "popularity_score": 97.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:amsterdam:canal-cruise",
        {
            "country": "NL",
            "city": "amsterdam",
            "region": "운하 지구",
            "name": "암스테르담 운하 크루즈",
            "name_en": "Amsterdam Canal Cruise",
            "address": "Stationsplein, 1012 AB Amsterdam",
            "latitude": 52.3791,
            "longitude": 4.8997,
            "category": "nature",
            "vibe_tags": ["감성", "힐링", "야간"],
            "description": "세계문화유산 165개 운하. 낮/야간 크루즈. 좁은 운하변 트위터 빌딩.",
            "cover_image": unsplash("photo-1499856871958-5b9627545d1a"),
            "rating": 4.5,
            "review_count": 32000,
            "price_level": 2,
            "popularity_score": 93.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:amsterdam:anne-frank-house",
        {
            "country": "NL",
            "city": "amsterdam",
            "region": "요르단",
            "name": "안네 프랑크 하우스",
            "name_en": "Anne Frank House",
            "address": "Westermarkt 20, 1016 GV Amsterdam",
            "latitude": 52.3752,
            "longitude": 4.8840,
            "category": "culture",
            "vibe_tags": ["역사", "교육", "조용"],
            "description": "안네의 일기 실제 배경 숨어살기 공간. 온라인 예약 2개월 전 매진.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.6,
            "review_count": 38000,
            "price_level": 2,
            "popularity_score": 93.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:amsterdam:jordaan-market",
        {
            "country": "NL",
            "city": "amsterdam",
            "region": "요르단",
            "name": "요르단 지구 & 노더마켓",
            "name_en": "Jordaan & Noordermarkt",
            "address": "Noordermarkt, 1015 MV Amsterdam",
            "latitude": 52.3778,
            "longitude": 4.8830,
            "category": "shopping",
            "vibe_tags": ["감성", "빈티지", "힐링"],
            "description": "아름다운 운하·갤러리·빈티지숍. 토요일 노더마켓 유기농 파머스마켓.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.5,
            "review_count": 19000,
            "price_level": 2,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:amsterdam:stroopwafel-cafe",
        {
            "country": "NL",
            "city": "amsterdam",
            "region": "중심가",
            "name": "스트룹와펠 & 네덜란드 간식",
            "name_en": "Dutch Stroopwafel Cafe",
            "address": "Nieuwmarkt, 1011 PW Amsterdam",
            "latitude": 52.3722,
            "longitude": 4.9008,
            "category": "cafe",
            "vibe_tags": ["현지느낌", "디저트", "감성"],
            "description": "네덜란드 국민 간식 스트룹와펠·키넌 치즈·헤링 청어. 로컬 카페 투어.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "rating": 4.4,
            "review_count": 8900,
            "price_level": 1,
            "popularity_score": 80.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:amsterdam:keukenhof",
        {
            "country": "NL",
            "city": "amsterdam",
            "region": "리세",
            "name": "쾨켄호프 튤립 공원",
            "name_en": "Keukenhof Garden",
            "address": "Stationsweg 166A, 2161 AM Lisse",
            "latitude": 52.2697,
            "longitude": 4.5461,
            "category": "nature",
            "vibe_tags": ["자연", "힐링", "포토"],
            "description": "세계 최대 튤립 공원. 매년 3~5월 800만 구근 개화. 암스테르담에서 40분.",
            "cover_image": unsplash("photo-1476820865390-c52aeebb9891"),
            "rating": 4.8,
            "review_count": 29000,
            "price_level": 2,
            "popularity_score": 94.0,
            "women_friendly": True,
        },
    ),
]

# ─── 바르셀로나 (7곳) ─────────────────────────────────────────────────────────
BARCELONA_SEED: list[tuple[str, dict]] = [
    (
        "seed:barcelona:sagrada-familia",
        {
            "country": "ES",
            "city": "barcelona",
            "region": "에이샴플레",
            "name": "사그라다 파밀리아",
            "name_en": "Sagrada Família",
            "address": "Carrer de Mallorca 401, 08013 Barcelona",
            "latitude": 41.4036,
            "longitude": 2.1744,
            "category": "culture",
            "vibe_tags": ["역사", "예술", "영적"],
            "description": "가우디 미완성 걸작 성당. 스테인드글라스 빛 유희. 예약 필수.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.8,
            "review_count": 72000,
            "price_level": 3,
            "popularity_score": 99.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:barcelona:park-guell",
        {
            "country": "ES",
            "city": "barcelona",
            "region": "그라시아",
            "name": "구엘 공원",
            "name_en": "Park Güell",
            "address": "08024 Barcelona",
            "latitude": 41.4145,
            "longitude": 2.1527,
            "category": "culture",
            "vibe_tags": ["예술", "자연", "포토"],
            "description": "가우디 모자이크 테라스에서 바르셀로나 전경. 유료 구역 시간제 예약.",
            "cover_image": unsplash("photo-1519922100285-cbc7e61a4fad"),
            "rating": 4.5,
            "review_count": 48000,
            "price_level": 2,
            "popularity_score": 95.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:barcelona:la-boqueria",
        {
            "country": "ES",
            "city": "barcelona",
            "region": "라발",
            "name": "라 보케리아 시장",
            "name_en": "La Boqueria Market",
            "address": "La Rambla 91, 08001 Barcelona",
            "latitude": 41.3818,
            "longitude": 2.1717,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌", "활기"],
            "description": "150년 역사 람블라스 대로 시장. 하몽·이베리코·스무디·타파스.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.4,
            "review_count": 41000,
            "price_level": 2,
            "popularity_score": 93.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:barcelona:gothic-quarter",
        {
            "country": "ES",
            "city": "barcelona",
            "region": "고딕지구",
            "name": "고딕 지구",
            "name_en": "Gothic Quarter (Barri Gòtic)",
            "address": "Barri Gòtic, 08002 Barcelona",
            "latitude": 41.3826,
            "longitude": 2.1769,
            "category": "culture",
            "vibe_tags": ["역사", "감성", "활기"],
            "description": "로마 시대 유적 위에 세워진 중세 미로 골목. 피카소 미술관 근접.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.5,
            "review_count": 31000,
            "price_level": 1,
            "popularity_score": 91.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:barcelona:barceloneta-beach",
        {
            "country": "ES",
            "city": "barcelona",
            "region": "바르셀로네타",
            "name": "바르셀로네타 해변",
            "name_en": "Barceloneta Beach",
            "address": "Barceloneta, 08003 Barcelona",
            "latitude": 41.3788,
            "longitude": 2.1905,
            "category": "nature",
            "vibe_tags": ["바다", "활기", "힐링"],
            "description": "도심 접근성 최고의 도시 해변. 파에야 맛집·서핑·비치 발리볼.",
            "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
            "rating": 4.3,
            "review_count": 28000,
            "price_level": 1,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:barcelona:casa-batllo",
        {
            "country": "ES",
            "city": "barcelona",
            "region": "에이샴플레",
            "name": "까사 바트요",
            "name_en": "Casa Batlló",
            "address": "Passeig de Gràcia 43, 08007 Barcelona",
            "latitude": 41.3916,
            "longitude": 2.1649,
            "category": "culture",
            "vibe_tags": ["예술", "모던", "역사"],
            "description": "가우디 설계 용의 등뼈 파사드. 야간 매직 나이트 공연. 예약 필수.",
            "cover_image": unsplash("photo-1519922100285-cbc7e61a4fad"),
            "rating": 4.7,
            "review_count": 29000,
            "price_level": 3,
            "popularity_score": 93.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:barcelona:el-born",
        {
            "country": "ES",
            "city": "barcelona",
            "region": "엘보른",
            "name": "엘 보른 지구",
            "name_en": "El Born / El Barri de la Ribera",
            "address": "El Born, 08003 Barcelona",
            "latitude": 41.3858,
            "longitude": 2.1818,
            "category": "cafe",
            "vibe_tags": ["트렌디", "감성", "활기"],
            "description": "바르셀로나 힙스터 거리. 피카소 미술관·독립 카페·빈티지숍 밀집.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "rating": 4.4,
            "review_count": 18000,
            "price_level": 2,
            "popularity_score": 87.0,
            "women_friendly": True,
        },
    ),
]

# ─── 로마 (7곳) ──────────────────────────────────────────────────────────────
ROME_SEED: list[tuple[str, dict]] = [
    (
        "seed:rome:colosseum",
        {
            "country": "IT",
            "city": "rome",
            "region": "콜로세움",
            "name": "콜로세움",
            "name_en": "Colosseum",
            "address": "Piazza del Colosseo 1, 00184 Roma RM",
            "latitude": 41.8902,
            "longitude": 12.4922,
            "category": "culture",
            "vibe_tags": ["역사", "웅장"],
            "description": "로마 제국 검투사 경기장. 7만 명 수용. 세계 7대 불가사의. 예약 필수.",
            "cover_image": unsplash("photo-1552832230-c0197dd311b5"),
            "rating": 4.7,
            "review_count": 82000,
            "price_level": 2,
            "popularity_score": 99.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:rome:trevi-fountain",
        {
            "country": "IT",
            "city": "rome",
            "region": "트레비",
            "name": "트레비 분수",
            "name_en": "Trevi Fountain",
            "address": "Piazza di Trevi, 00187 Roma RM",
            "latitude": 41.9009,
            "longitude": 12.4833,
            "category": "photospot",
            "vibe_tags": ["감성", "역사", "야간"],
            "description": "로마 최대 바로크 분수. 동전 하나 던지면 다시 로마에 온다는 전설.",
            "cover_image": unsplash("photo-1552832230-c0197dd311b5"),
            "rating": 4.6,
            "review_count": 61000,
            "price_level": 1,
            "popularity_score": 97.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:rome:vatican",
        {
            "country": "VA",
            "city": "rome",
            "region": "바티칸",
            "name": "바티칸 박물관 & 성 베드로 대성당",
            "name_en": "Vatican Museums & St. Peter's Basilica",
            "address": "00120 Città del Vaticano",
            "latitude": 41.9065,
            "longitude": 12.4536,
            "category": "culture",
            "vibe_tags": ["역사", "영적", "예술"],
            "description": "시스티나 예배당 천장화·미켈란젤로 피에타. 교황청 국가 입장. 예약 필수.",
            "cover_image": unsplash("photo-1552832230-c0197dd311b5"),
            "rating": 4.8,
            "review_count": 68000,
            "price_level": 3,
            "popularity_score": 98.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:rome:roman-forum",
        {
            "country": "IT",
            "city": "rome",
            "region": "포로 로마노",
            "name": "포로 로마노 (고대 로마 광장)",
            "name_en": "Roman Forum",
            "address": "Via Sacra, 00186 Roma RM",
            "latitude": 41.8925,
            "longitude": 12.4853,
            "category": "culture",
            "vibe_tags": ["역사", "조용"],
            "description": "고대 로마 정치·경제 중심지. 신전·개선문 유적. 콜로세움 통합권 사용.",
            "cover_image": unsplash("photo-1552832230-c0197dd311b5"),
            "rating": 4.5,
            "review_count": 42000,
            "price_level": 2,
            "popularity_score": 92.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:rome:gelato-fatamorgana",
        {
            "country": "IT",
            "city": "rome",
            "region": "나보나",
            "name": "파타 모르가나 젤라토",
            "name_en": "Fatamorgana Gelato",
            "address": "Via Laurina 10, 00187 Roma RM",
            "latitude": 41.9062,
            "longitude": 12.4762,
            "category": "dessert",
            "vibe_tags": ["맛집", "현지느낌", "디저트"],
            "description": "무글루텐·비건 젤라토 명가. 바질-레몬·고르곤졸라-호두 등 독특한 맛.",
            "cover_image": unsplash("photo-1558303982-f8f6d2d3e4ee"),
            "rating": 4.6,
            "review_count": 9800,
            "price_level": 1,
            "popularity_score": 85.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:rome:piazza-navona",
        {
            "country": "IT",
            "city": "rome",
            "region": "나보나",
            "name": "나보나 광장",
            "name_en": "Piazza Navona",
            "address": "Piazza Navona, 00186 Roma RM",
            "latitude": 41.8992,
            "longitude": 12.4731,
            "category": "culture",
            "vibe_tags": ["감성", "활기", "역사"],
            "description": "베르니니 분수 3개를 품은 바로크 광장. 노천 카페·화가·거리 공연 일상.",
            "cover_image": unsplash("photo-1499856871958-5b9627545d1a"),
            "rating": 4.5,
            "review_count": 32000,
            "price_level": 2,
            "popularity_score": 91.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:rome:trastevere",
        {
            "country": "IT",
            "city": "rome",
            "region": "트라스테베레",
            "name": "트라스테베레 지구",
            "name_en": "Trastevere",
            "address": "Trastevere, 00153 Roma RM",
            "latitude": 41.8893,
            "longitude": 12.4726,
            "category": "restaurant",
            "vibe_tags": ["현지느낌", "야간", "맛집"],
            "description": "로마인이 사랑하는 로컬 지구. 골목 이탈리안 트라토리아·와인바·갤러리.",
            "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
            "rating": 4.5,
            "review_count": 22000,
            "price_level": 2,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
]

# ─── 프라하 (6곳) ─────────────────────────────────────────────────────────────
PRAGUE_SEED: list[tuple[str, dict]] = [
    (
        "seed:prague:charles-bridge",
        {
            "country": "CZ",
            "city": "prague",
            "region": "스타레 메스토",
            "name": "카를교",
            "name_en": "Charles Bridge",
            "address": "Karlův most, 110 00 Praha 1",
            "latitude": 50.0865,
            "longitude": 14.4114,
            "category": "photospot",
            "vibe_tags": ["역사", "감성", "야간"],
            "description": "14세기 고딕 석교. 30개 성인 조각. 새벽 안개와 야경이 가장 아름다움.",
            "cover_image": unsplash("photo-1519922100285-cbc7e61a4fad"),
            "rating": 4.7,
            "review_count": 45000,
            "price_level": 1,
            "popularity_score": 97.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:prague:old-town-square",
        {
            "country": "CZ",
            "city": "prague",
            "region": "스타레 메스토",
            "name": "구시가지 광장 & 천문시계",
            "name_en": "Old Town Square & Astronomical Clock",
            "address": "Staroměstské nám., 110 00 Praha 1",
            "latitude": 50.0875,
            "longitude": 14.4208,
            "category": "culture",
            "vibe_tags": ["역사", "활기", "감성"],
            "description": "매시간 정각 인형 등장하는 600년 천문시계. 틴 성당·성 니콜라스 교회.",
            "cover_image": unsplash("photo-1519922100285-cbc7e61a4fad"),
            "rating": 4.6,
            "review_count": 38000,
            "price_level": 1,
            "popularity_score": 95.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:prague:prague-castle",
        {
            "country": "CZ",
            "city": "prague",
            "region": "흐라드차니",
            "name": "프라하 성",
            "name_en": "Prague Castle",
            "address": "119 08 Praha 1-Hradčany",
            "latitude": 50.0909,
            "longitude": 14.4001,
            "category": "culture",
            "vibe_tags": ["역사", "자연", "뷰포인트"],
            "description": "세계 최대 고성. 성 비투스 대성당·왕궁·황금 골목. 구시가지 조망.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.6,
            "review_count": 41000,
            "price_level": 2,
            "popularity_score": 95.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:prague:josefov",
        {
            "country": "CZ",
            "city": "prague",
            "region": "요제포프",
            "name": "요제포프 유대인 지구",
            "name_en": "Josefov Jewish Quarter",
            "address": "Josefov, 110 00 Praha 1",
            "latitude": 50.0902,
            "longitude": 14.4175,
            "category": "culture",
            "vibe_tags": ["역사", "조용", "교육"],
            "description": "유럽에서 가장 잘 보존된 유대인 게토. 6개 시나고그·카프카 생가.",
            "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
            "rating": 4.4,
            "review_count": 18000,
            "price_level": 2,
            "popularity_score": 82.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:prague:trdelnik-cafe",
        {
            "country": "CZ",
            "city": "prague",
            "region": "구시가지",
            "name": "뜨르들리크 & 체코 맥주",
            "name_en": "Trdelník & Czech Beer",
            "address": "Staré Město, 110 00 Praha 1",
            "latitude": 50.0880,
            "longitude": 14.4188,
            "category": "dessert",
            "vibe_tags": ["현지느낌", "디저트", "활기"],
            "description": "체코 굴뚝 과자 뜨르들리크와 체코 필스너 우르켈. 0.5리터 생맥주 1~2달러.",
            "cover_image": unsplash("photo-1558303982-f8f6d2d3e4ee"),
            "rating": 4.3,
            "review_count": 12000,
            "price_level": 1,
            "popularity_score": 82.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:prague:petrin-hill",
        {
            "country": "CZ",
            "city": "prague",
            "region": "말라 스트라나",
            "name": "페트린 언덕 & 에펠탑 전망대",
            "name_en": "Petřín Hill & Lookout Tower",
            "address": "Petřín, 150 00 Praha 5",
            "latitude": 50.0830,
            "longitude": 14.3992,
            "category": "nature",
            "vibe_tags": ["자연", "뷰포인트", "힐링"],
            "description": "케이블카 또는 산책로 오를 수 있는 언덕. 프라하 전경 360도 조망.",
            "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
            "rating": 4.5,
            "review_count": 21000,
            "price_level": 1,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
]

# 전체 유럽 시드
EUROPE_SEED = [
    *PARIS_SEED,
    *LONDON_SEED,
    *AMSTERDAM_SEED,
    *BARCELONA_SEED,
    *ROME_SEED,
    *PRAGUE_SEED,
]
