"""후쿠오카 큐레이션 시드 (15곳)."""

from .helpers import unsplash

FUKUOKA_SEED: list[tuple[str, dict]] = [
    (
        "seed:fukuoka:ohori-park",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "오호리",
            "name": "오호리 공원",
            "name_en": "Ohori Park",
            "address": "Ohorikoen, Chuo Ward, Fukuoka",
            "latitude": 33.5850,
            "longitude": 130.3752,
            "category": "nature",
            "vibe_tags": ["힐링", "자연", "조용"],
            "description": "후쿠오카 도심의 대형 호수 공원. 산책과 사이클링 코스로 유명.",
            "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
            "rating": 4.4,
            "review_count": 3200,
            "price_level": 1,
            "popularity_score": 85.0,
            "women_friendly": True,
            "safety_score": 5,
        },
    ),
    (
        "seed:fukuoka:hakata-ramen-shin-shin",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "하카타",
            "name": "신신 라멘",
            "name_en": "Hakata Ramen Shin-Shin",
            "address": "3-2-19 Tenjin, Chuo Ward, Fukuoka",
            "latitude": 33.5900,
            "longitude": 130.3985,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌", "활기"],
            "description": "후쿠오카 하카타 돈코츠 라멘의 정수. 진한 돼지뼈 육수.",
            "cover_image": unsplash("photo-1569718212165-3a8278d5f624"),
            "rating": 4.6,
            "review_count": 4500,
            "price_level": 1,
            "popularity_score": 92.0,
        },
    ),
    (
        "seed:fukuoka:canal-city",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "하카타",
            "name": "캐널시티 하카타",
            "name_en": "Canal City Hakata",
            "address": "1-2 Sumiyoshi, Hakata Ward, Fukuoka",
            "latitude": 33.5894,
            "longitude": 130.4108,
            "category": "shopping",
            "vibe_tags": ["모던", "활기", "트렌디"],
            "description": "운하가 흐르는 복합쇼핑몰. 분수쇼, 영화관, 레스토랑 집결.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.2,
            "review_count": 5600,
            "price_level": 2,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:fukuoka:atago-shrine",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "니시구",
            "name": "아타고 신사",
            "name_en": "Atago Shrine",
            "address": "2-7-1 Atago, Nishi Ward, Fukuoka",
            "latitude": 33.5985,
            "longitude": 130.3520,
            "category": "culture",
            "vibe_tags": ["힐링", "영적", "조용"],
            "description": "후쿠오카 만을 조망하는 언덕 위 신사. 일몰 뷰 포인트.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.3,
            "review_count": 1800,
            "price_level": 1,
            "popularity_score": 72.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:fukuoka:yanagibashi-market",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "하카타",
            "name": "야나기바시 시장",
            "name_en": "Yanagibashi Rengo Market",
            "address": "2-7-27 Haruyoshi, Chuo Ward, Fukuoka",
            "latitude": 33.5876,
            "longitude": 130.4015,
            "category": "shopping",
            "vibe_tags": ["현지느낌", "활기", "맛집"],
            "description": "하카타의 부엌이라 불리는 전통 시장. 신선한 해산물과 현지 식재료.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.5,
            "review_count": 2100,
            "price_level": 1,
            "popularity_score": 80.0,
        },
    ),
    (
        "seed:fukuoka:tsurugi-shrine-dazaifu",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "다자이후",
            "name": "다자이후 텐만구",
            "name_en": "Dazaifu Tenmangu Shrine",
            "address": "4-7-1 Saifu, Dazaifu City, Fukuoka",
            "latitude": 33.5215,
            "longitude": 130.5337,
            "category": "culture",
            "vibe_tags": ["역사", "전통", "영적"],
            "description": "학문의 신을 모시는 천년 역사의 신사. 우메가에모치 떡으로 유명.",
            "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
            "rating": 4.5,
            "review_count": 8900,
            "price_level": 1,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:fukuoka:tenjin-underground-mall",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "텐진",
            "name": "텐진 지하상가",
            "name_en": "Tenjin Underground Shopping Mall",
            "address": "2-1 Tenjin, Chuo Ward, Fukuoka",
            "latitude": 33.5903,
            "longitude": 130.3983,
            "category": "shopping",
            "vibe_tags": ["모던", "활기", "트렌디"],
            "description": "유럽풍 아케이드 스타일의 지하 쇼핑 거리. 160여 개 매장.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.1,
            "review_count": 6700,
            "price_level": 2,
            "popularity_score": 82.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:fukuoka:momochi-beach",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "모모치",
            "name": "모모치 해변공원",
            "name_en": "Momochi Beach Park",
            "address": "Momochihama, Sawara Ward, Fukuoka",
            "latitude": 33.5933,
            "longitude": 130.3505,
            "category": "nature",
            "vibe_tags": ["활기", "바다", "힐링"],
            "description": "시내 접근성 최고의 인공 해변. 후쿠오카 타워와 함께 석양 명소.",
            "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
            "rating": 4.2,
            "review_count": 3400,
            "price_level": 1,
            "popularity_score": 78.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:fukuoka:yatai-nakasu",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "나카스",
            "name": "나카스 야타이 포장마차 거리",
            "name_en": "Nakasu Yatai Street",
            "address": "Nakasu, Hakata Ward, Fukuoka",
            "latitude": 33.5915,
            "longitude": 130.4078,
            "category": "bar",
            "vibe_tags": ["현지느낌", "활기", "야간"],
            "description": "후쿠오카 명물 야외 포장마차. 나카스강변 라멘·꼬치구이·사케.",
            "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
            "rating": 4.4,
            "review_count": 5200,
            "price_level": 2,
            "popularity_score": 88.0,
        },
    ),
    (
        "seed:fukuoka:fukuoka-tower",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "모모치",
            "name": "후쿠오카 타워",
            "name_en": "Fukuoka Tower",
            "address": "2-3-26 Momochihama, Sawara Ward, Fukuoka",
            "latitude": 33.5942,
            "longitude": 130.3542,
            "category": "photospot",
            "vibe_tags": ["뷰포인트", "모던", "활기"],
            "description": "해변에 서 있는 234m 높이의 전망 타워. 하카타만 360도 뷰.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.1,
            "review_count": 4100,
            "price_level": 2,
            "popularity_score": 75.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:fukuoka:hakata-machiya-museum",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "하카타",
            "name": "하카타 마치야 민속관",
            "name_en": "Hakata Machiya Folk Museum",
            "address": "6-10 Reizenmachi, Hakata Ward, Fukuoka",
            "latitude": 33.5995,
            "longitude": 130.4145,
            "category": "culture",
            "vibe_tags": ["역사", "전통", "조용"],
            "description": "메이지~쇼와 시대 하카타 상인의 생활을 재현한 민속박물관.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.0,
            "review_count": 1200,
            "price_level": 1,
            "popularity_score": 62.0,
        },
    ),
    (
        "seed:fukuoka:itoshima-surf",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "이토시마",
            "name": "이토시마 해안",
            "name_en": "Itoshima Coast",
            "address": "Itoshima City, Fukuoka",
            "latitude": 33.5615,
            "longitude": 130.2032,
            "category": "nature",
            "vibe_tags": ["바다", "힐링", "자연"],
            "description": "후쿠오카 근교의 숨겨진 해안. 서퍼 카페·석양·후타미가우라 부부바위.",
            "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
            "rating": 4.6,
            "review_count": 2800,
            "price_level": 1,
            "popularity_score": 84.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:fukuoka:ippudo-hakata",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "하카타",
            "name": "잇푸도 하카타 본점",
            "name_en": "Ippudo Hakata",
            "address": "1-13-14 Daimyo, Chuo Ward, Fukuoka",
            "latitude": 33.5921,
            "longitude": 130.3975,
            "category": "restaurant",
            "vibe_tags": ["맛집", "활기"],
            "description": "전 세계 지점을 둔 하카타 라멘 체인의 본점. 정통 크리미 돈코츠.",
            "cover_image": unsplash("photo-1569718212165-3a8278d5f624"),
            "rating": 4.4,
            "review_count": 7200,
            "price_level": 1,
            "popularity_score": 90.0,
        },
    ),
    (
        "seed:fukuoka:coffee-yamamoto",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "야쿠인",
            "name": "커피 야마모토",
            "name_en": "Coffee Yamamoto",
            "address": "1-1-7 Yakuin, Chuo Ward, Fukuoka",
            "latitude": 33.5798,
            "longitude": 130.4018,
            "category": "cafe",
            "vibe_tags": ["조용", "빈티지", "감성"],
            "description": "쇼와 시대 레트로 분위기의 킷사텐(다방). 사이폰 커피 전문.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "rating": 4.3,
            "review_count": 890,
            "price_level": 2,
            "popularity_score": 70.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:fukuoka:kushida-shrine",
        {
            "country": "JP",
            "city": "fukuoka",
            "region": "하카타",
            "name": "쿠시다 신사",
            "name_en": "Kushida Shrine",
            "address": "1-41 Kamikawabatamachi, Hakata Ward, Fukuoka",
            "latitude": 33.5976,
            "longitude": 130.4120,
            "category": "culture",
            "vibe_tags": ["전통", "역사", "영적"],
            "description": "하카타 기온 야마카사 축제의 본거지 신사. 대형 야마 장식 상설 전시.",
            "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
            "rating": 4.4,
            "review_count": 2600,
            "price_level": 1,
            "popularity_score": 79.0,
            "women_friendly": True,
        },
    ),
]
