"""강릉 큐레이션 시드 (10곳)."""
from .helpers import unsplash

GANGNEUNG_SEED: list[tuple[str, dict]] = [
    ("seed:gangneung:gyeongpo-beach", {
        "country": "KR", "city": "gangneung", "region": "경포",
        "name": "경포대 해변", "name_en": "Gyeongpo Beach",
        "address": "강원도 강릉시 강문동",
        "latitude": 37.7968, "longitude": 128.9100,
        "category": "nature", "vibe_tags": ["바다", "힐링", "자연"],
        "description": "강릉 최대 해변. 8km 백사장과 에메랄드 바다. 일출 명소.",
        "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
        "rating": 4.4, "review_count": 12000, "price_level": 1,
        "popularity_score": 90.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:gangneung:cafe-street", {
        "country": "KR", "city": "gangneung", "region": "안목",
        "name": "안목 해변 카페거리", "name_en": "Anmok Beach Cafe Street",
        "address": "강원도 강릉시 창해로14번길",
        "latitude": 37.7762, "longitude": 128.9322,
        "category": "cafe", "vibe_tags": ["바다뷰", "감성", "힐링"],
        "description": "동해 바다를 바라보며 커피를. 커피 자판기 문화에서 발전한 카페 성지.",
        "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
        "rating": 4.5, "review_count": 9800, "price_level": 2,
        "popularity_score": 92.0, "women_friendly": True,
    }),
    ("seed:gangneung:ojukheon", {
        "country": "KR", "city": "gangneung", "region": "죽헌동",
        "name": "오죽헌", "name_en": "Ojukheon House",
        "address": "강원도 강릉시 율곡로 3139번길 24",
        "latitude": 37.7789, "longitude": 128.8820,
        "category": "culture", "vibe_tags": ["역사", "전통", "조용"],
        "description": "신사임당·율곡 이이 생가. 5만원권·1000원권 지폐의 배경. 대나무숲 산책.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "rating": 4.3, "review_count": 6500, "price_level": 1,
        "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:gangneung:daegwallyeong-sheep-farm", {
        "country": "KR", "city": "gangneung", "region": "대관령",
        "name": "대관령 양떼목장", "name_en": "Daegwallyeong Sheep Farm",
        "address": "강원도 평창군 대관령면 대관령마루길 483-32",
        "latitude": 37.6802, "longitude": 128.7338,
        "category": "nature", "vibe_tags": ["자연", "힐링", "가족"],
        "description": "1000m 고원 위 양떼목장. 양 먹이주기 체험, 광활한 초지 산책로.",
        "cover_image": unsplash("photo-1500534314209-a25ddb2bd429"),
        "rating": 4.4, "review_count": 8900, "price_level": 2,
        "popularity_score": 85.0, "women_friendly": True,
    }),
    ("seed:gangneung:soondubu-jjigae", {
        "country": "KR", "city": "gangneung", "region": "경포",
        "name": "강릉 초당 순두부 마을", "name_en": "Chodang Soondubu Village",
        "address": "강원도 강릉시 초당동",
        "latitude": 37.7889, "longitude": 128.9078,
        "category": "restaurant", "vibe_tags": ["맛집", "현지느낌"],
        "description": "바닷물로 굳힌 초당 순두부 원산지. 뚝배기 순두부찌개 전문 식당가.",
        "cover_image": unsplash("photo-1574484284002-952d92456975"),
        "rating": 4.5, "review_count": 11000, "price_level": 1,
        "popularity_score": 90.0,
    }),
    ("seed:gangneung:jumunjin-beach", {
        "country": "KR", "city": "gangneung", "region": "주문진",
        "name": "주문진 해변 & 방파제", "name_en": "Jumunjin Beach",
        "address": "강원도 강릉시 주문진읍 주문진리",
        "latitude": 37.8985, "longitude": 128.8185,
        "category": "nature", "vibe_tags": ["바다", "힐링", "감성"],
        "description": "드라마 '도깨비' 촬영지. 빨간 등대와 방파제 산책로. 생선구이 맛집.",
        "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
        "rating": 4.3, "review_count": 7200, "price_level": 1,
        "popularity_score": 83.0, "women_friendly": True,
    }),
    ("seed:gangneung:gyeongpo-lake", {
        "country": "KR", "city": "gangneung", "region": "경포",
        "name": "경포호", "name_en": "Gyeongpo Lake",
        "address": "강원도 강릉시 경포로 365",
        "latitude": 37.7910, "longitude": 128.9012,
        "category": "nature", "vibe_tags": ["힐링", "자연", "조용"],
        "description": "바다와 인접한 담수호. 철새 도래지, 벚꽃 시즌 최고 명소.",
        "cover_image": unsplash("photo-1476820865390-c52aeebb9891"),
        "rating": 4.4, "review_count": 5600, "price_level": 1,
        "popularity_score": 80.0, "women_friendly": True,
    }),
    ("seed:gangneung:gangneung-coffee-museum", {
        "country": "KR", "city": "gangneung", "region": "왕산",
        "name": "강릉 커피 박물관", "name_en": "Gangneung Coffee Museum",
        "address": "강원도 강릉시 왕산면 왕산로 59",
        "latitude": 37.7038, "longitude": 128.8395,
        "category": "cafe", "vibe_tags": ["감성", "조용"],
        "description": "커피 역사와 문화를 담은 박물관. 산간 시골 가옥 개조 분위기.",
        "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
        "rating": 4.1, "review_count": 2100, "price_level": 2,
        "popularity_score": 68.0, "women_friendly": True,
    }),
    ("seed:gangneung:haslla-art-world", {
        "country": "KR", "city": "gangneung", "region": "정동진",
        "name": "하슬라 아트월드", "name_en": "Haslla Art World",
        "address": "강원도 강릉시 강동면 율곡로 1441",
        "latitude": 37.7195, "longitude": 129.0138,
        "category": "culture", "vibe_tags": ["예술", "자연", "감성"],
        "description": "바다를 배경으로 한 야외 조각공원+미술관. 피노키오 박물관 포함.",
        "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
        "rating": 4.2, "review_count": 3800, "price_level": 2,
        "popularity_score": 72.0, "women_friendly": True,
    }),
    ("seed:gangneung:jeongdongjin-sunrise", {
        "country": "KR", "city": "gangneung", "region": "정동진",
        "name": "정동진 일출", "name_en": "Jeongdongjin Sunrise",
        "address": "강원도 강릉시 강동면 정동역길 17",
        "latitude": 37.6978, "longitude": 129.0370,
        "category": "photospot", "vibe_tags": ["일출", "바다", "뷰포인트"],
        "description": "세계에서 바다와 가장 가까운 기차역. 새해 일출 명소 1위.",
        "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
        "rating": 4.6, "review_count": 9200, "price_level": 1,
        "popularity_score": 88.0, "women_friendly": True,
    }),
]
