"""경주 큐레이션 시드 (10곳)."""

from .helpers import unsplash

GYEONGJU_SEED: list[tuple[str, dict]] = [
    (
        "seed:gyeongju:bulguksa",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "불국동",
            "name": "불국사",
            "name_en": "Bulguksa Temple",
            "address": "경상북도 경주시 불국로 385",
            "latitude": 35.7897,
            "longitude": 129.3316,
            "category": "culture",
            "vibe_tags": ["역사", "영적", "전통"],
            "description": "유네스코 세계문화유산. 신라 문화 정수. 다보탑·석가탑·청운교.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.6,
            "review_count": 19000,
            "price_level": 1,
            "popularity_score": 95.0,
            "women_friendly": True,
            "safety_score": 5,
        },
    ),
    (
        "seed:gyeongju:seokguram-grotto",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "진현동",
            "name": "석굴암",
            "name_en": "Seokguram Grotto",
            "address": "경상북도 경주시 불국로 873-243",
            "latitude": 35.7944,
            "longitude": 129.3464,
            "category": "culture",
            "vibe_tags": ["역사", "영적", "자연"],
            "description": "토함산 정상 석굴 사원. 세계문화유산. 통일신라 석조 불상 걸작.",
            "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
            "rating": 4.7,
            "review_count": 12000,
            "price_level": 1,
            "popularity_score": 93.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:gyeongju:daereungwon-tumuli",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "황남동",
            "name": "대릉원 (신라 고분군)",
            "name_en": "Daereungwon Tumuli Park",
            "address": "경상북도 경주시 계림로 9",
            "latitude": 35.8388,
            "longitude": 129.2174,
            "category": "culture",
            "vibe_tags": ["역사", "자연", "조용"],
            "description": "신라 왕릉 23기 집결 고분 공원. 천마총 내부 관람 가능.",
            "cover_image": unsplash("photo-1476820865390-c52aeebb9891"),
            "rating": 4.4,
            "review_count": 15000,
            "price_level": 1,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:gyeongju:cheomseongdae",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "인왕동",
            "name": "첨성대",
            "name_en": "Cheomseongdae Observatory",
            "address": "경상북도 경주시 첨성로 169-5",
            "latitude": 35.8349,
            "longitude": 129.2195,
            "category": "culture",
            "vibe_tags": ["역사", "포토"],
            "description": "동양 최고(最古) 천문대. 7세기 신라 석조 건축물. 야간 조명이 아름다움.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.3,
            "review_count": 14000,
            "price_level": 1,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:gyeongju:anapji-pond",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "인왕동",
            "name": "동궁과 월지 (안압지)",
            "name_en": "Donggung Palace and Wolji Pond",
            "address": "경상북도 경주시 원화로 102",
            "latitude": 35.8343,
            "longitude": 129.2248,
            "category": "culture",
            "vibe_tags": ["역사", "야간", "감성"],
            "description": "신라 별궁 연못. 야간 조명 반영이 절경. 경주 야경 포토 1번지.",
            "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
            "rating": 4.6,
            "review_count": 16000,
            "price_level": 1,
            "popularity_score": 92.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:gyeongju:gyerim-forest",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "교동",
            "name": "계림",
            "name_en": "Gyerim Forest",
            "address": "경상북도 경주시 교동",
            "latitude": 35.8375,
            "longitude": 129.2145,
            "category": "nature",
            "vibe_tags": ["자연", "조용", "힐링"],
            "description": "신라 왕성 옆 천년 숲. 울창한 고목 사이 산책로. 신라 김씨 시조 탄생 설화지.",
            "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
            "rating": 4.3,
            "review_count": 4800,
            "price_level": 1,
            "popularity_score": 76.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:gyeongju:hwang리단-gil",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "황남동",
            "name": "황리단길",
            "name_en": "Hwangridangil Street",
            "address": "경상북도 경주시 황남동",
            "latitude": 35.8320,
            "longitude": 129.2132,
            "category": "cafe",
            "vibe_tags": ["감성", "트렌디", "활기"],
            "description": "한옥을 개조한 카페·레스토랑·편집숍이 밀집한 감성 거리. 전통+현대 조화.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "rating": 4.4,
            "review_count": 11000,
            "price_level": 2,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:gyeongju:gampo-beach",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "양북면",
            "name": "감포 해변",
            "name_en": "Gampo Beach",
            "address": "경상북도 경주시 감포읍",
            "latitude": 35.7969,
            "longitude": 129.4960,
            "category": "nature",
            "vibe_tags": ["바다", "힐링", "조용"],
            "description": "붐비지 않는 경주 동해안 해변. 신라 문무왕 수중릉(대왕암) 근처.",
            "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
            "rating": 4.2,
            "review_count": 3100,
            "price_level": 1,
            "popularity_score": 70.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:gyeongju:gyeongju-bread",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "성동동",
            "name": "경주 황남빵",
            "name_en": "Gyeongju Hwangnam Bread",
            "address": "경상북도 경주시 태종로 783",
            "latitude": 35.8302,
            "longitude": 129.2175,
            "category": "dessert",
            "vibe_tags": ["현지느낌", "디저트"],
            "description": "경주 70년 전통 팥소 과자빵. 경주 여행 필수 기념품.",
            "cover_image": unsplash("photo-1558303982-f8f6d2d3e4ee"),
            "rating": 4.5,
            "review_count": 8900,
            "price_level": 1,
            "popularity_score": 87.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:gyeongju:national-museum",
        {
            "country": "KR",
            "city": "gyeongju",
            "region": "인왕동",
            "name": "국립경주박물관",
            "name_en": "Gyeongju National Museum",
            "address": "경상북도 경주시 일정로 186",
            "latitude": 35.8298,
            "longitude": 129.2268,
            "category": "culture",
            "vibe_tags": ["역사", "조용", "교육"],
            "description": "신라 유물 4만 점 소장. 성덕대왕신종(에밀레종) 실물 감상.",
            "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
            "rating": 4.4,
            "review_count": 7200,
            "price_level": 1,
            "popularity_score": 84.0,
            "women_friendly": True,
        },
    ),
]
