"""히로시마 큐레이션 시드 (10곳)."""
from .helpers import unsplash

HIROSHIMA_SEED: list[tuple[str, dict]] = [
    ("seed:hiroshima:peace-memorial-park", {
        "country": "JP", "city": "hiroshima", "region": "나카구",
        "name": "히로시마 평화기념공원", "name_en": "Hiroshima Peace Memorial Park",
        "address": "1-2 Nakajimacho, Naka Ward, Hiroshima",
        "latitude": 34.3953, "longitude": 132.4534,
        "category": "culture", "vibe_tags": ["역사", "조용", "영적"],
        "description": "원폭 피해를 기억하는 세계평화 상징 공원. 원폭돔·평화기념관 포함.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "rating": 4.7, "review_count": 22000, "price_level": 1,
        "popularity_score": 96.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:hiroshima:atomic-bomb-dome", {
        "country": "JP", "city": "hiroshima", "region": "나카구",
        "name": "원폭 돔", "name_en": "Atomic Bomb Dome (Genbaku Dome)",
        "address": "1-10 Otemachi, Naka Ward, Hiroshima",
        "latitude": 34.3957, "longitude": 132.4535,
        "category": "culture", "vibe_tags": ["역사", "영적"],
        "description": "세계문화유산. 1945년 원폭 투하 후 유일하게 원형 보존된 건물.",
        "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
        "rating": 4.8, "review_count": 29000, "price_level": 1,
        "popularity_score": 98.0, "women_friendly": True,
    }),
    ("seed:hiroshima:miyajima-island", {
        "country": "JP", "city": "hiroshima", "region": "하쓰카이치",
        "name": "미야지마 (이쓰쿠시마 신사)", "name_en": "Miyajima Island / Itsukushima Shrine",
        "address": "1-1 Miyajimacho, Hatsukaichi City",
        "latitude": 34.2954, "longitude": 132.3197,
        "category": "culture", "vibe_tags": ["역사", "자연", "영적"],
        "description": "바다 위에 뜬 도리이. 세계문화유산 이쓰쿠시마 신사. 사슴과 함께 산책.",
        "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
        "rating": 4.8, "review_count": 35000, "price_level": 2,
        "popularity_score": 98.0, "women_friendly": True,
    }),
    ("seed:hiroshima:okonomimura", {
        "country": "JP", "city": "hiroshima", "region": "나카구",
        "name": "오코노미무라", "name_en": "Okonomimura",
        "address": "6-6 Shintenchicho, Naka Ward, Hiroshima",
        "latitude": 34.3922, "longitude": 132.4602,
        "category": "restaurant", "vibe_tags": ["맛집", "현지느낌", "활기"],
        "description": "히로시마 풍 오코노미야키(소바 들어간 층층이 구이) 전문점 25개 밀집.",
        "cover_image": unsplash("photo-1574484284002-952d92456975"),
        "rating": 4.3, "review_count": 7800, "price_level": 1,
        "popularity_score": 87.0,
    }),
    ("seed:hiroshima:hiroshima-castle", {
        "country": "JP", "city": "hiroshima", "region": "나카구",
        "name": "히로시마 성", "name_en": "Hiroshima Castle",
        "address": "21-1 Motomachi, Naka Ward, Hiroshima",
        "latitude": 34.4018, "longitude": 132.4580,
        "category": "culture", "vibe_tags": ["역사", "전통"],
        "description": "원폭으로 소실 후 1958년 재건. 5층 천수각 내부 역사박물관 운영.",
        "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
        "rating": 4.1, "review_count": 8200, "price_level": 1,
        "popularity_score": 80.0, "women_friendly": True,
    }),
    ("seed:hiroshima:shukkei-en-garden", {
        "country": "JP", "city": "hiroshima", "region": "나카구",
        "name": "슛케이엔 정원", "name_en": "Shukkeien Garden",
        "address": "2-11 Kaminoborimachi, Naka Ward, Hiroshima",
        "latitude": 34.3998, "longitude": 132.4673,
        "category": "nature", "vibe_tags": ["전통", "조용", "힐링"],
        "description": "에도 초기 1620년 조성 정원. 연못·다리·정자가 어우러진 회유식.",
        "cover_image": unsplash("photo-1476820865390-c52aeebb9891"),
        "rating": 4.3, "review_count": 3500, "price_level": 1,
        "popularity_score": 74.0, "women_friendly": True,
    }),
    ("seed:hiroshima:hiroshima-museum-art", {
        "country": "JP", "city": "hiroshima", "region": "나카구",
        "name": "히로시마 미술관", "name_en": "Hiroshima Museum of Art",
        "address": "3-2 Motomachi, Naka Ward, Hiroshima",
        "latitude": 34.3980, "longitude": 132.4555,
        "category": "culture", "vibe_tags": ["예술", "조용", "모던"],
        "description": "인상파·야수파 등 19~20세기 서양미술 컬렉션. 르느와르·고흐 소장.",
        "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
        "rating": 4.2, "review_count": 2800, "price_level": 2,
        "popularity_score": 68.0, "women_friendly": True,
    }),
    ("seed:hiroshima:mt-misen-miyajima", {
        "country": "JP", "city": "hiroshima", "region": "하쓰카이치",
        "name": "미센 산 (미야지마)", "name_en": "Mt. Misen",
        "address": "Miyajimacho, Hatsukaichi City",
        "latitude": 34.2828, "longitude": 132.3212,
        "category": "nature", "vibe_tags": ["자연", "트레킹", "뷰포인트"],
        "description": "미야지마 최고봉 535m. 홍법대사 전설의 불꽃. 세토 내해 절경 조망.",
        "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
        "rating": 4.5, "review_count": 5100, "price_level": 2,
        "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:hiroshima:momiji-manju-shop", {
        "country": "JP", "city": "hiroshima", "region": "하쓰카이치",
        "name": "모미지 만주 가게", "name_en": "Momiji Manju Shop",
        "address": "Miyajimacho, Hatsukaichi City",
        "latitude": 34.2968, "longitude": 132.3208,
        "category": "dessert", "vibe_tags": ["현지느낌", "디저트", "활기"],
        "description": "단풍잎 모양 히로시마 대표 화과자 '모미지 만주' 즉석 판매.",
        "cover_image": unsplash("photo-1558303982-f8f6d2d3e4ee"),
        "rating": 4.4, "review_count": 6200, "price_level": 1,
        "popularity_score": 84.0, "women_friendly": True,
    }),
    ("seed:hiroshima:oyster-teppan", {
        "country": "JP", "city": "hiroshima", "region": "나카구",
        "name": "히로시마 굴 철판구이", "name_en": "Hiroshima Oyster Teppan",
        "address": "Nagarekawa-cho, Naka Ward, Hiroshima",
        "latitude": 34.3903, "longitude": 132.4588,
        "category": "restaurant", "vibe_tags": ["맛집", "현지느낌"],
        "description": "일본 최대 굴 생산지 히로시마의 굴 요리 전문점. 생굴·구이·굴튀김.",
        "cover_image": unsplash("photo-1519984388953-d2406bc725e1"),
        "rating": 4.5, "review_count": 4300, "price_level": 2,
        "popularity_score": 85.0,
    }),
]
