"""제주 큐레이션 시드 (8곳)."""
from .helpers import unsplash

JEJU_SEED: list[tuple[str, dict]] = [
    ("seed:jeju:hyeopjae-beach", {
        "country": "KR", "city": "jeju", "region": "한림",
        "name": "협재해변", "name_en": "Hyeopjae Beach",
        "address": "제주 제주시 한림읍 협재리",
        "latitude": 33.3941, "longitude": 126.2398,
        "category": "nature", "vibe_tags": ["감성", "한적", "인스타"],
        "description": "에메랄드빛 바다와 비양도 배경. 제주 대표 해변.",
        "cover_image": unsplash("photo-1505228395891-9a51e7e86bf6"),
        "instagram_hashtag": "#협재해변", "rating": 4.6, "review_count": 14000,
        "popularity_score": 92.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:jeju:seopjikoji", {
        "country": "KR", "city": "jeju", "region": "성산",
        "name": "섭지코지", "name_en": "Seopjikoji",
        "address": "제주 서귀포시 성산읍 고성리",
        "latitude": 33.4252, "longitude": 126.9293,
        "category": "photospot", "vibe_tags": ["감성", "한적", "분위기"],
        "description": "성산일출봉과 함께 보는 해안 절경.",
        "cover_image": unsplash("photo-1493976040374-85c8e12f0c0e"),
        "instagram_hashtag": "#섭지코지", "rating": 4.5, "review_count": 8900,
        "popularity_score": 85.0, "women_friendly": True,
    }),
    ("seed:jeju:seongsan-ilchulbong", {
        "country": "KR", "city": "jeju", "region": "성산",
        "name": "성산일출봉", "name_en": "Seongsan Ilchulbong",
        "address": "제주 서귀포시 성산읍 성산리 1",
        "latitude": 33.4584, "longitude": 126.9426,
        "category": "nature", "vibe_tags": ["감성", "분위기"],
        "description": "유네스코 세계자연유산. 일출 명소.",
        "cover_image": unsplash("photo-1480796927426-f609979314bd"),
        "instagram_hashtag": "#성산일출봉", "rating": 4.6, "review_count": 19000,
        "price_level": 1, "popularity_score": 90.0, "safety_score": 5,
    }),
    ("seed:jeju:cafe-monocle", {
        "country": "KR", "city": "jeju", "region": "구좌",
        "name": "카페 모노클", "name_en": "Cafe Monocle",
        "address": "제주 제주시 구좌읍 행원로11길 31",
        "latitude": 33.5358, "longitude": 126.7977,
        "category": "cafe", "vibe_tags": ["모던", "감성", "한적"],
        "description": "바다 보이는 통창 카페. 제주 동쪽 핫플.",
        "cover_image": unsplash("photo-1442512595331-e89e73853f31"),
        "instagram_hashtag": "#카페모노클", "rating": 4.5, "review_count": 2100,
        "price_level": 2, "popularity_score": 76.0, "women_friendly": True,
    }),
    ("seed:jeju:anthracite-jeju", {
        "country": "KR", "city": "jeju", "region": "한림",
        "name": "앤트러사이트 제주 한림", "name_en": "Anthracite Jeju Hallim",
        "address": "제주 제주시 한림읍 한림로 564",
        "latitude": 33.4117, "longitude": 126.2641,
        "category": "cafe", "vibe_tags": ["빈티지", "감성"],
        "description": "전분 공장을 개조한 로스터리. 빈티지 감성.",
        "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
        "instagram_hashtag": "#anthracitecoffee", "rating": 4.4, "review_count": 3200,
        "price_level": 2, "popularity_score": 78.0, "women_friendly": True,
    }),
    ("seed:jeju:doldam-haenyeo", {
        "country": "KR", "city": "jeju", "region": "성산",
        "name": "돌담해녀촌", "name_en": "Doldam Haenyeo Village",
        "address": "제주 서귀포시 성산읍 고성리",
        "latitude": 33.4308, "longitude": 126.9251,
        "category": "restaurant", "vibe_tags": ["레트로", "분위기"],
        "description": "해녀가 직접 잡은 해산물. 제주 전통 그대로.",
        "cover_image": unsplash("photo-1579871494447-9811cf80d66c"),
        "instagram_hashtag": "#해녀촌", "rating": 4.3, "review_count": 1800,
        "price_level": 3, "popularity_score": 71.0,
    }),
    ("seed:jeju:hallasan", {
        "country": "KR", "city": "jeju", "region": "한라산",
        "name": "한라산 국립공원", "name_en": "Hallasan National Park",
        "address": "제주 제주시 1100로 2070-61",
        "latitude": 33.3617, "longitude": 126.5319,
        "category": "nature", "vibe_tags": ["한적", "조용"],
        "description": "한국에서 가장 높은 산. 5월 철쭉·가을 단풍.",
        "cover_image": unsplash("photo-1490772888775-55fceea286b8"),
        "instagram_hashtag": "#한라산", "rating": 4.7, "review_count": 11000,
        "popularity_score": 84.0, "safety_score": 4,
    }),
    ("seed:jeju:dongmun-market", {
        "country": "KR", "city": "jeju", "region": "제주시",
        "name": "동문재래시장", "name_en": "Dongmun Traditional Market",
        "address": "제주 제주시 관덕로14길 20",
        "latitude": 33.5126, "longitude": 126.5266,
        "category": "shopping", "vibe_tags": ["레트로", "활기"],
        "description": "제주 대표 재래시장. 흑돼지·감귤·오메기떡.",
        "cover_image": unsplash("photo-1604754742629-3e0498a8f4ee"),
        "instagram_hashtag": "#동문시장", "rating": 4.3, "review_count": 6700,
        "price_level": 2, "popularity_score": 80.0,
    }),
]
