"""전주 큐레이션 시드 (8곳)."""
from .helpers import unsplash

JEONJU_SEED: list[tuple[str, dict]] = [
    ("seed:jeonju:hanok-village", {
        "country": "KR", "city": "jeonju", "region": "교동",
        "name": "전주 한옥마을", "name_en": "Jeonju Hanok Village",
        "address": "전라북도 전주시 완산구 기린대로 99",
        "latitude": 35.8150, "longitude": 127.1539,
        "category": "culture", "vibe_tags": ["전통", "감성", "활기"],
        "description": "700채 전통 한옥 밀집. 한복 체험·전통 공예·비빔밥의 성지.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "rating": 4.5, "review_count": 28000, "price_level": 2,
        "popularity_score": 95.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:jeonju:bibimbap", {
        "country": "KR", "city": "jeonju", "region": "중앙동",
        "name": "전주 비빔밥 골목", "name_en": "Jeonju Bibimbap Street",
        "address": "전라북도 전주시 완산구 전동",
        "latitude": 35.8145, "longitude": 127.1520,
        "category": "restaurant", "vibe_tags": ["맛집", "현지느낌"],
        "description": "전주 3대 명물 비빔밥 원조 거리. 놋그릇 비빔밥과 콩나물국밥.",
        "cover_image": unsplash("photo-1574484284002-952d92456975"),
        "rating": 4.6, "review_count": 18000, "price_level": 1,
        "popularity_score": 93.0,
    }),
    ("seed:jeonju:gyeonggijeon-shrine", {
        "country": "KR", "city": "jeonju", "region": "교동",
        "name": "경기전", "name_en": "Gyeonggijeon Shrine",
        "address": "전라북도 전주시 완산구 태조로 44",
        "latitude": 35.8152, "longitude": 127.1538,
        "category": "culture", "vibe_tags": ["역사", "전통", "조용"],
        "description": "조선 태조 이성계 어진 봉안 사당. 한옥마을 내 최고 역사 명소.",
        "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
        "rating": 4.4, "review_count": 12000, "price_level": 1,
        "popularity_score": 88.0, "women_friendly": True,
    }),
    ("seed:jeonju:hanbok-experience", {
        "country": "KR", "city": "jeonju", "region": "교동",
        "name": "한복 체험 거리", "name_en": "Hanbok Experience Street",
        "address": "전라북도 전주시 완산구 최명희길",
        "latitude": 35.8162, "longitude": 127.1545,
        "category": "culture", "vibe_tags": ["감성", "전통", "활기"],
        "description": "한복 대여 후 한옥마을 산책. 수십 개 한복 대여점이 밀집.",
        "cover_image": unsplash("photo-1558618666-fcd25c85cd64"),
        "rating": 4.5, "review_count": 9800, "price_level": 2,
        "popularity_score": 88.0, "women_friendly": True,
    }),
    ("seed:jeonju:omokdae", {
        "country": "KR", "city": "jeonju", "region": "교동",
        "name": "오목대 전망대", "name_en": "Omokdae Pavilion",
        "address": "전라북도 전주시 완산구 기린대로 55",
        "latitude": 35.8132, "longitude": 127.1579,
        "category": "photospot", "vibe_tags": ["뷰포인트", "역사", "조용"],
        "description": "한옥마을 전체를 내려다보는 언덕 정자. 이성계 승전 기념지.",
        "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
        "rating": 4.3, "review_count": 6800, "price_level": 1,
        "popularity_score": 80.0, "women_friendly": True,
    }),
    ("seed:jeonju:nambu-market", {
        "country": "KR", "city": "jeonju", "region": "중앙동",
        "name": "남부시장 청년몰", "name_en": "Nambu Market Youth Market",
        "address": "전라북도 전주시 완산구 풍남문3길 1",
        "latitude": 35.8105, "longitude": 127.1488,
        "category": "shopping", "vibe_tags": ["활기", "트렌디", "현지느낌"],
        "description": "전통 시장 내 청년 창업 공간. 수제 먹거리·공방·야시장 금요일 운영.",
        "cover_image": unsplash("photo-1542838132-92c53300491e"),
        "rating": 4.3, "review_count": 7200, "price_level": 1,
        "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:jeonju:ppalganmat-makgeolli", {
        "country": "KR", "city": "jeonju", "region": "삼천동",
        "name": "삼천동 막걸리 골목", "name_en": "Samcheondong Makgeolli Street",
        "address": "전라북도 전주시 완산구 삼천동",
        "latitude": 35.7985, "longitude": 127.1272,
        "category": "bar", "vibe_tags": ["현지느낌", "맛집", "야간"],
        "description": "전주 막걸리와 무한 안주. 막걸리 한 주전자 시키면 무한 안주 제공.",
        "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
        "rating": 4.4, "review_count": 8500, "price_level": 1,
        "popularity_score": 85.0,
    }),
    ("seed:jeonju:jaman-mural-village", {
        "country": "KR", "city": "jeonju", "region": "교동",
        "name": "자만벽화마을", "name_en": "Jaman Mural Village",
        "address": "전라북도 전주시 완산구 자만동",
        "latitude": 35.8088, "longitude": 127.1575,
        "category": "photospot", "vibe_tags": ["감성", "예술", "조용"],
        "description": "오목대 아래 달동네 계단 골목을 채운 벽화 마을. 전주 한옥마을 근접.",
        "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
        "rating": 4.2, "review_count": 5200, "price_level": 1,
        "popularity_score": 76.0, "women_friendly": True,
    }),
]
