"""고베 큐레이션 시드 (10곳)."""
from .helpers import unsplash

KOBE_SEED: list[tuple[str, dict]] = [
    ("seed:kobe:kitano-ijinkan", {
        "country": "JP", "city": "kobe", "region": "기타노",
        "name": "기타노 이진칸 거리", "name_en": "Kitano Ijinkan",
        "address": "Kitanocho, Chuo Ward, Kobe",
        "latitude": 34.6977, "longitude": 135.1928,
        "category": "culture", "vibe_tags": ["역사", "감성", "조용"],
        "description": "메이지 시대 외국인 거주 서양식 저택 군. 20여 채 빌라 내부 관람 가능.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "rating": 4.2, "review_count": 8500, "price_level": 2,
        "popularity_score": 85.0, "women_friendly": True,
    }),
    ("seed:kobe:kobe-beef-mouriya", {
        "country": "JP", "city": "kobe", "region": "산노미야",
        "name": "모리야 고베비프", "name_en": "Mouriya Kobe Beef",
        "address": "2-1-17 Nakayamatedori, Chuo Ward, Kobe",
        "latitude": 34.6933, "longitude": 135.1940,
        "category": "restaurant", "vibe_tags": ["고급", "맛집"],
        "description": "150년 역사의 고베 비프 원조 레스토랑. 눈앞에서 굽는 철판구이.",
        "cover_image": unsplash("photo-1544025162-d76694265947"),
        "rating": 4.7, "review_count": 5200, "price_level": 4,
        "popularity_score": 90.0,
    }),
    ("seed:kobe:meriken-park", {
        "country": "JP", "city": "kobe", "region": "나카구",
        "name": "메리켄 파크", "name_en": "Meriken Park",
        "address": "Hatoba-cho, Chuo Ward, Kobe",
        "latitude": 34.6858, "longitude": 135.1924,
        "category": "nature", "vibe_tags": ["힐링", "바다", "활기"],
        "description": "고베 항구를 바라보는 해안 공원. 고베 포트타워·해양박물관 근접.",
        "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
        "rating": 4.3, "review_count": 9800, "price_level": 1,
        "popularity_score": 84.0, "women_friendly": True,
    }),
    ("seed:kobe:nunobiki-herb-garden", {
        "country": "JP", "city": "kobe", "region": "기타구",
        "name": "누노비키 허브 정원", "name_en": "Nunobiki Herb Garden",
        "address": "1-4-3 Kitanocho, Chuo Ward, Kobe",
        "latitude": 34.7095, "longitude": 135.1905,
        "category": "nature", "vibe_tags": ["힐링", "자연", "여성친화"],
        "description": "롭웨이로 올라가는 산 위 허브 정원. 고베 시내와 바다가 한눈에.",
        "cover_image": unsplash("photo-1476820865390-c52aeebb9891"),
        "rating": 4.4, "review_count": 6700, "price_level": 2,
        "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:kobe:chinatown-nankinmachi", {
        "country": "JP", "city": "kobe", "region": "나카구",
        "name": "난킨마치 (고베 차이나타운)", "name_en": "Nankinmachi Chinatown",
        "address": "Motomachidori 2-chome, Chuo Ward, Kobe",
        "latitude": 34.6878, "longitude": 135.1892,
        "category": "restaurant", "vibe_tags": ["맛집", "활기", "현지느낌"],
        "description": "100년 역사의 차이나타운. 돼지고기 중화만두·라오 빙 디저트 인기.",
        "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
        "rating": 4.1, "review_count": 11000, "price_level": 1,
        "popularity_score": 87.0, "women_friendly": True,
    }),
    ("seed:kobe:arima-onsen", {
        "country": "JP", "city": "kobe", "region": "아리마",
        "name": "아리마 온천", "name_en": "Arima Onsen",
        "address": "Arima-cho, Kita Ward, Kobe",
        "latitude": 34.7993, "longitude": 135.2448,
        "category": "hotel", "vibe_tags": ["힐링", "온천", "전통"],
        "description": "일본 3대 명탕. 금탕(철분)·은탕(탄산수소) 두 가지 온천수. 고베 시내에서 40분.",
        "cover_image": unsplash("photo-1500534314209-a25ddb2bd429"),
        "rating": 4.6, "review_count": 7200, "price_level": 3,
        "popularity_score": 88.0, "women_friendly": True,
    }),
    ("seed:kobe:hyogo-pref-museum-art", {
        "country": "JP", "city": "kobe", "region": "나다구",
        "name": "효고현립 미술관", "name_en": "Hyogo Prefectural Museum of Art",
        "address": "1-1-1 Wakihama Kaigan-dori, Nada Ward, Kobe",
        "latitude": 34.7005, "longitude": 135.2235,
        "category": "culture", "vibe_tags": ["예술", "조용", "모던"],
        "description": "안도 다다오 설계 해안 미술관. 일본 현대미술 대규모 컬렉션.",
        "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
        "rating": 4.3, "review_count": 3800, "price_level": 2,
        "popularity_score": 74.0, "women_friendly": True,
    }),
    ("seed:kobe:rokko-mountain", {
        "country": "JP", "city": "kobe", "region": "롯코",
        "name": "롯코산 야경", "name_en": "Mt. Rokko",
        "address": "Rokko-san, Nada Ward, Kobe",
        "latitude": 34.7615, "longitude": 135.2488,
        "category": "photospot", "vibe_tags": ["뷰포인트", "자연", "야간"],
        "description": "천만 달러 야경으로 유명한 롯코산 정상. 고베~오사카만 파노라마 전망.",
        "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
        "rating": 4.5, "review_count": 8900, "price_level": 2,
        "popularity_score": 88.0, "women_friendly": True,
    }),
    ("seed:kobe:kobe-fashion-museum", {
        "country": "JP", "city": "kobe", "region": "롯코아일랜드",
        "name": "고베 패션 미술관", "name_en": "Kobe Fashion Museum",
        "address": "2-9-1 Koyocho-Naka, Higashinada Ward, Kobe",
        "latitude": 34.7025, "longitude": 135.2748,
        "category": "culture", "vibe_tags": ["예술", "감성", "조용"],
        "description": "세계 패션 역사를 담은 박물관. 17세기~현재 의상 및 패션 사진 컬렉션.",
        "cover_image": unsplash("photo-1558618666-fcd25c85cd64"),
        "rating": 4.1, "review_count": 2200, "price_level": 2,
        "popularity_score": 67.0, "women_friendly": True,
    }),
    ("seed:kobe:harbor-cruise", {
        "country": "JP", "city": "kobe", "region": "나카구",
        "name": "고베 항구 크루즈", "name_en": "Kobe Harbor Cruise",
        "address": "Nakatomihama, Chuo Ward, Kobe",
        "latitude": 34.6852, "longitude": 135.1958,
        "category": "nature", "vibe_tags": ["바다", "힐링", "야간"],
        "description": "고베 항구 선상 크루즈. 낮 시간 관광 또는 야경 야간 선박 선택 가능.",
        "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
        "rating": 4.3, "review_count": 4100, "price_level": 2,
        "popularity_score": 78.0, "women_friendly": True,
    }),
]
