"""교토 큐레이션 시드 (10곳)."""
from .helpers import unsplash

KYOTO_SEED: list[tuple[str, dict]] = [
    ("seed:kyoto:fushimi-inari", {
        "country": "JP", "city": "kyoto", "region": "후시미",
        "name": "후시미 이나리 신사", "name_en": "Fushimi Inari Taisha",
        "address": "68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto",
        "latitude": 34.9671, "longitude": 135.7727,
        "category": "photospot", "vibe_tags": ["분위기", "감성", "인스타"],
        "description": "천 개의 토리이가 늘어선 산길. 새벽 방문이 한적.",
        "cover_image": unsplash("photo-1493997181344-712f2f19d87a"),
        "instagram_hashtag": "#fushimiinari", "rating": 4.7, "review_count": 31000,
        "popularity_score": 96.0, "safety_score": 5,
    }),
    ("seed:kyoto:kinkaku-ji", {
        "country": "JP", "city": "kyoto", "region": "키타",
        "name": "킨카쿠지 (금각사)", "name_en": "Kinkaku-ji",
        "address": "1 Kinkakujicho, Kita Ward, Kyoto",
        "latitude": 35.0394, "longitude": 135.7292,
        "category": "culture", "vibe_tags": ["고급", "분위기", "조용"],
        "description": "황금빛 누각이 호수에 비치는 교토 대표 사찰.",
        "cover_image": unsplash("photo-1545569310-c55c4c98e02d"),
        "instagram_hashtag": "#kinkakuji", "rating": 4.6, "review_count": 28000,
        "price_level": 1, "popularity_score": 93.0, "safety_score": 5,
    }),
    ("seed:kyoto:arashiyama-bamboo", {
        "country": "JP", "city": "kyoto", "region": "아라시야마",
        "name": "아라시야마 대나무숲", "name_en": "Arashiyama Bamboo Grove",
        "address": "Ukyo Ward, Sagaogurayama Tabuchiyamacho, Kyoto",
        "latitude": 35.0170, "longitude": 135.6716,
        "category": "nature", "vibe_tags": ["감성", "한적", "조용"],
        "description": "초록 대나무 터널. 이른 아침이 가장 신비롭다.",
        "cover_image": unsplash("photo-1493976040374-85c8e12f0c0e"),
        "instagram_hashtag": "#arashiyama", "rating": 4.5, "review_count": 19000,
        "popularity_score": 90.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:kyoto:gion-hanamikoji", {
        "country": "JP", "city": "kyoto", "region": "기온",
        "name": "기온 하나미코지", "name_en": "Gion Hanamikoji",
        "address": "Hanamikoji-dori, Higashiyama Ward, Kyoto",
        "latitude": 35.0036, "longitude": 135.7755,
        "category": "photospot", "vibe_tags": ["레트로", "분위기", "감성"],
        "description": "마이코·게이코가 거니는 전통 거리. 저녁이 더 분위기 있다.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "instagram_hashtag": "#gion", "rating": 4.5, "review_count": 11000,
        "popularity_score": 87.0, "women_friendly": True,
    }),
    ("seed:kyoto:nishiki-market", {
        "country": "JP", "city": "kyoto", "region": "나카교",
        "name": "니시키 시장", "name_en": "Nishiki Market",
        "address": "Nishikikoji-dori, Nakagyo Ward, Kyoto",
        "latitude": 35.0049, "longitude": 135.7644,
        "category": "shopping", "vibe_tags": ["레트로", "활기"],
        "description": "교토의 부엌. 츠케모노·교과시·말차 디저트.",
        "cover_image": unsplash("photo-1604754742629-3e0498a8f4ee"),
        "instagram_hashtag": "#nishikimarket", "rating": 4.4, "review_count": 9800,
        "price_level": 2, "popularity_score": 84.0,
    }),
    ("seed:kyoto:arabica-higashiyama", {
        "country": "JP", "city": "kyoto", "region": "히가시야마",
        "name": "% 아라비카 교토 히가시야마", "name_en": "% Arabica Kyoto Higashiyama",
        "address": "87-5 Hoshinocho, Higashiyama Ward, Kyoto",
        "latitude": 35.0008, "longitude": 135.7805,
        "category": "cafe", "vibe_tags": ["모던", "감성", "인스타"],
        "description": "야사카탑 옆 미니멀 카페. 라떼 한 잔의 인생샷.",
        "cover_image": unsplash("photo-1442512595331-e89e73853f31"),
        "instagram_hashtag": "#arabica", "rating": 4.5, "review_count": 6800,
        "price_level": 2, "popularity_score": 91.0, "women_friendly": True,
    }),
    ("seed:kyoto:tsujiri-honten", {
        "country": "JP", "city": "kyoto", "region": "기온",
        "name": "츠지리 본점", "name_en": "Tsujiri Honten",
        "address": "573-3 Gionmachi Minamigawa, Higashiyama Ward, Kyoto",
        "latitude": 35.0035, "longitude": 135.7765,
        "category": "dessert", "vibe_tags": ["고급", "감성"],
        "description": "150년 역사의 우지 말차 디저트.",
        "cover_image": unsplash("photo-1488477181946-6428a0291777"),
        "instagram_hashtag": "#tsujiri", "rating": 4.5, "review_count": 4200,
        "price_level": 3, "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:kyoto:philosophers-path", {
        "country": "JP", "city": "kyoto", "region": "사쿄",
        "name": "철학의 길", "name_en": "Philosopher's Path",
        "address": "Sakyo Ward, Kyoto",
        "latitude": 35.0270, "longitude": 135.7948,
        "category": "nature", "vibe_tags": ["한적", "감성", "조용"],
        "description": "수로를 따라 이어진 산책로. 봄 벚꽃이 절경.",
        "cover_image": unsplash("photo-1522383225653-ed111181a951"),
        "instagram_hashtag": "#philosopherspath", "rating": 4.5, "review_count": 4800,
        "popularity_score": 76.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:kyoto:kiyomizu-dera", {
        "country": "JP", "city": "kyoto", "region": "히가시야마",
        "name": "기요미즈데라", "name_en": "Kiyomizu-dera",
        "address": "1-294 Kiyomizu, Higashiyama Ward, Kyoto",
        "latitude": 34.9949, "longitude": 135.7851,
        "category": "culture", "vibe_tags": ["분위기", "감성"],
        "description": "교토 시내 한눈에 보이는 절벽 사찰. 단풍·벚꽃 명소.",
        "cover_image": unsplash("photo-1480796927426-f609979314bd"),
        "instagram_hashtag": "#kiyomizudera", "rating": 4.6, "review_count": 24000,
        "price_level": 1, "popularity_score": 92.0, "safety_score": 5,
    }),
    ("seed:kyoto:omen-arashiyama", {
        "country": "JP", "city": "kyoto", "region": "아라시야마",
        "name": "오멘 아라시야마", "name_en": "Omen Arashiyama",
        "address": "Tabuchiyamacho, Ukyo Ward, Kyoto",
        "latitude": 35.0151, "longitude": 135.6791,
        "category": "restaurant", "vibe_tags": ["조용", "가성비"],
        "description": "수제 우동 명가. 채소를 풍성하게 올린다.",
        "cover_image": unsplash("photo-1623341214825-9f4f963727da"),
        "instagram_hashtag": "#omenudon", "rating": 4.3, "review_count": 1100,
        "price_level": 2, "popularity_score": 70.0, "women_friendly": True,
    }),
]
