"""나고야 큐레이션 시드 (10곳)."""
from .helpers import unsplash

NAGOYA_SEED: list[tuple[str, dict]] = [
    ("seed:nagoya:nagoya-castle", {
        "country": "JP", "city": "nagoya", "region": "나카구",
        "name": "나고야 성", "name_en": "Nagoya Castle",
        "address": "1-1 Honmaru, Naka Ward, Nagoya",
        "latitude": 35.1856, "longitude": 136.8995,
        "category": "culture", "vibe_tags": ["역사", "전통"],
        "description": "금색 범고래 장식으로 유명한 에도시대 성. 니노마루 정원 산책 가능.",
        "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
        "rating": 4.4, "review_count": 14000, "price_level": 2,
        "popularity_score": 90.0, "women_friendly": True,
    }),
    ("seed:nagoya:atsuta-jingu", {
        "country": "JP", "city": "nagoya", "region": "아츠타구",
        "name": "아츠타 신궁", "name_en": "Atsuta Jingu Shrine",
        "address": "1-1-1 Jingu, Atsuta Ward, Nagoya",
        "latitude": 35.1281, "longitude": 136.9069,
        "category": "culture", "vibe_tags": ["영적", "역사", "자연"],
        "description": "일본 3대 신궁 중 하나. 삼종신기 중 '천총운검' 봉안. 울창한 숲.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "rating": 4.5, "review_count": 8900, "price_level": 1,
        "popularity_score": 88.0, "women_friendly": True,
    }),
    ("seed:nagoya:sakae-oasis21", {
        "country": "JP", "city": "nagoya", "region": "사카에",
        "name": "오아시스21", "name_en": "Oasis 21",
        "address": "1-11-1 Higashisakura, Higashi Ward, Nagoya",
        "latitude": 35.1701, "longitude": 136.9068,
        "category": "photospot", "vibe_tags": ["모던", "활기", "야간"],
        "description": "유리로 만든 우주선 형태의 복합시설. 지붕 위 산책로에서 TV탑 조망.",
        "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
        "rating": 4.2, "review_count": 7200, "price_level": 1,
        "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:nagoya:miso-katsu-yabaton", {
        "country": "JP", "city": "nagoya", "region": "사카에",
        "name": "야바톤 미소카츠", "name_en": "Yabaton Miso Katsu",
        "address": "2-1-21 Osu, Naka Ward, Nagoya",
        "latitude": 35.1597, "longitude": 136.9050,
        "category": "restaurant", "vibe_tags": ["맛집", "현지느낌"],
        "description": "나고야 명물 미소카츠 원조. 진한 핫초미소 소스로 덮인 돈카츠.",
        "cover_image": unsplash("photo-1519984388953-d2406bc725e1"),
        "rating": 4.5, "review_count": 6800, "price_level": 2,
        "popularity_score": 90.0,
    }),
    ("seed:nagoya:osu-shopping", {
        "country": "JP", "city": "nagoya", "region": "오스",
        "name": "오스 상점가", "name_en": "Osu Shopping Street",
        "address": "Osu, Naka Ward, Nagoya",
        "latitude": 35.1601, "longitude": 136.9025,
        "category": "shopping", "vibe_tags": ["활기", "트렌디", "현지느낌"],
        "description": "1200개 점포 아케이드. 빈티지·코스프레·B급 음식 뒤섞인 개성 강한 거리.",
        "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
        "rating": 4.3, "review_count": 9500, "price_level": 1,
        "popularity_score": 85.0, "women_friendly": True,
    }),
    ("seed:nagoya:toyota-museum", {
        "country": "JP", "city": "nagoya", "region": "나가쿠테",
        "name": "토요타 박물관", "name_en": "Toyota Automobile Museum",
        "address": "41-100 Yokomichi, Nagakute City",
        "latitude": 35.1756, "longitude": 137.0512,
        "category": "culture", "vibe_tags": ["역사", "모던"],
        "description": "자동차 역사 120년을 담은 박물관. 세계 명차 140여 대 전시.",
        "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
        "rating": 4.4, "review_count": 3200, "price_level": 2,
        "popularity_score": 78.0,
    }),
    ("seed:nagoya:hitsumabushi-bincho", {
        "country": "JP", "city": "nagoya", "region": "사카에",
        "name": "히츠마부시 빈쵸", "name_en": "Hitsumabushi Bincho",
        "address": "3-7-21 Nishiki, Naka Ward, Nagoya",
        "latitude": 35.1720, "longitude": 136.9010,
        "category": "restaurant", "vibe_tags": ["맛집", "고급"],
        "description": "나고야 명물 장어덮밥 '히츠마부시' 전문점. 3가지 방식으로 즐기는 장어.",
        "cover_image": unsplash("photo-1574484284002-952d92456975"),
        "rating": 4.6, "review_count": 4500, "price_level": 3,
        "popularity_score": 87.0,
    }),
    ("seed:nagoya:inuyama-castle", {
        "country": "JP", "city": "nagoya", "region": "이누야마",
        "name": "이누야마 성", "name_en": "Inuyama Castle",
        "address": "65-2 Kitakoken, Inuyama City, Aichi",
        "latitude": 35.3860, "longitude": 136.9423,
        "category": "culture", "vibe_tags": ["역사", "자연", "조용"],
        "description": "현존하는 일본 최고(最古) 목조 천수각. 기소강 절경이 내려다보임.",
        "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
        "rating": 4.5, "review_count": 6700, "price_level": 1,
        "popularity_score": 84.0, "women_friendly": True,
    }),
    ("seed:nagoya:coffee-mornings", {
        "country": "JP", "city": "nagoya", "region": "나카구",
        "name": "나고야 모닝 카페 (코메다 커피)", "name_en": "Komeda Coffee",
        "address": "2-7-13 Sakae, Naka Ward, Nagoya",
        "latitude": 35.1685, "longitude": 136.9032,
        "category": "cafe", "vibe_tags": ["현지느낌", "힐링", "조용"],
        "description": "나고야 아침 문화 '모닝'. 음료 주문 시 무료 두꺼운 토스트+삶은 달걀.",
        "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
        "rating": 4.2, "review_count": 8900, "price_level": 1,
        "popularity_score": 83.0, "women_friendly": True,
    }),
    ("seed:nagoya:legoland", {
        "country": "JP", "city": "nagoya", "region": "미나토구",
        "name": "레고랜드 재팬", "name_en": "Legoland Japan",
        "address": "2-2-1 Kinjo Futo, Minato Ward, Nagoya",
        "latitude": 35.0998, "longitude": 136.8778,
        "category": "nature", "vibe_tags": ["가족", "활기"],
        "description": "아시아 최초 레고랜드. 어린이 동반 가족 여행에 최적. 항구 전망.",
        "cover_image": unsplash("photo-1518020382113-a7e8fc38eac9"),
        "rating": 3.9, "review_count": 5200, "price_level": 3,
        "popularity_score": 70.0, "women_friendly": True,
    }),
]
