"""오키나와 큐레이션 시드 (12곳)."""
from .helpers import unsplash

OKINAWA_SEED: list[tuple[str, dict]] = [
    ("seed:okinawa:churaumi-aquarium", {
        "country": "JP", "city": "okinawa", "region": "모토부",
        "name": "오키나와 추라우미 수족관", "name_en": "Okinawa Churaumi Aquarium",
        "address": "1421-5 Ishikawa, Motobu-cho, Kunigami-gun",
        "latitude": 26.6939, "longitude": 127.8782,
        "category": "culture", "vibe_tags": ["가족", "활기", "자연"],
        "description": "세계 최대급 수조 '흑조의 바다'. 고래상어와 쥐가오리를 가까이서.",
        "cover_image": unsplash("photo-1518020382113-a7e8fc38eac9"),
        "rating": 4.7, "review_count": 18000, "price_level": 3,
        "popularity_score": 95.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:okinawa:shuri-castle", {
        "country": "JP", "city": "okinawa", "region": "나하",
        "name": "슈리성", "name_en": "Shuri Castle",
        "address": "1-2 Kinjo-cho, Shuri, Naha City",
        "latitude": 26.2169, "longitude": 127.7195,
        "category": "culture", "vibe_tags": ["역사", "문화", "전통"],
        "description": "류큐 왕국의 궁전. 2019년 화재 후 복원 중. 세계문화유산.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "rating": 4.4, "review_count": 12000, "price_level": 2,
        "popularity_score": 92.0, "women_friendly": True,
    }),
    ("seed:okinawa:kokusai-dori", {
        "country": "JP", "city": "okinawa", "region": "나하",
        "name": "국제거리", "name_en": "Kokusai-dori Street",
        "address": "Kokusai-dori, Naha City",
        "latitude": 26.2124, "longitude": 127.6880,
        "category": "shopping", "vibe_tags": ["활기", "트렌디", "현지느낌"],
        "description": "나하 최대 쇼핑·음식 거리. 사탕수수 주스·チャンプルー·기념품 천국.",
        "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
        "rating": 4.1, "review_count": 9800, "price_level": 2,
        "popularity_score": 87.0, "women_friendly": True,
    }),
    ("seed:okinawa:emerald-beach", {
        "country": "JP", "city": "okinawa", "region": "모토부",
        "name": "에메랄드 비치", "name_en": "Emerald Beach",
        "address": "1424 Ishikawa, Motobu-cho, Kunigami-gun",
        "latitude": 26.6980, "longitude": 127.8820,
        "category": "nature", "vibe_tags": ["바다", "힐링", "자연"],
        "description": "추라우미 수족관 근처 청정 해변. 에메랄드빛 바다에서 스노클링 가능.",
        "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
        "rating": 4.6, "review_count": 7200, "price_level": 1,
        "popularity_score": 90.0, "women_friendly": True,
    }),
    ("seed:okinawa:cape-manzamo", {
        "country": "JP", "city": "okinawa", "region": "온나손",
        "name": "만자모 곶", "name_en": "Cape Manzamo",
        "address": "Manzamo, Onna-son, Kunigami-gun",
        "latitude": 26.4838, "longitude": 127.8582,
        "category": "photospot", "vibe_tags": ["자연", "뷰포인트", "힐링"],
        "description": "코끼리 모양 절벽 위에서 바라보는 동중국해 절경. 일몰 포인트.",
        "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
        "rating": 4.4, "review_count": 5600, "price_level": 1,
        "popularity_score": 85.0, "women_friendly": True,
    }),
    ("seed:okinawa:yachimun-no-sato", {
        "country": "JP", "city": "okinawa", "region": "요미탄",
        "name": "야치문 도자기 마을", "name_en": "Yachimun no Sato",
        "address": "Yachimun no Sato, Yomitan-son",
        "latitude": 26.4225, "longitude": 127.7375,
        "category": "shopping", "vibe_tags": ["전통", "예술", "조용"],
        "description": "류큐 전통 도예 마을. 50개 이상 도예가 공방 집결. 핸드메이드 기념품.",
        "cover_image": unsplash("photo-1558618666-fcd25c85cd64"),
        "rating": 4.4, "review_count": 2800, "price_level": 2,
        "popularity_score": 76.0, "women_friendly": True,
    }),
    ("seed:okinawa:american-village", {
        "country": "JP", "city": "okinawa", "region": "차탄",
        "name": "아메리칸 빌리지", "name_en": "American Village Chatan",
        "address": "9-1 Mihama, Chatan-cho, Nakagami-gun",
        "latitude": 26.3148, "longitude": 127.7565,
        "category": "shopping", "vibe_tags": ["트렌디", "활기", "야간"],
        "description": "미군기지 반환 후 개발된 엔터테인먼트 타운. 관람차·쇼핑·레스토랑.",
        "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
        "rating": 4.0, "review_count": 7400, "price_level": 2,
        "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:okinawa:nakijin-castle", {
        "country": "JP", "city": "okinawa", "region": "나키진",
        "name": "나키진 성터", "name_en": "Nakijin Castle Ruins",
        "address": "5101 Imadomari, Nakijin-son",
        "latitude": 26.6822, "longitude": 127.9097,
        "category": "culture", "vibe_tags": ["역사", "자연", "조용"],
        "description": "세계유산 류큐 왕국 성곽. 벚꽃 명소. 성 위에서 동중국해 조망.",
        "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
        "rating": 4.3, "review_count": 3100, "price_level": 1,
        "popularity_score": 72.0, "women_friendly": True,
    }),
    ("seed:okinawa:makishi-public-market", {
        "country": "JP", "city": "okinawa", "region": "나하",
        "name": "마키시 공설시장", "name_en": "Makishi Public Market",
        "address": "2-10-1 Matsuo, Naha City",
        "latitude": 26.2118, "longitude": 127.6825,
        "category": "restaurant", "vibe_tags": ["현지느낌", "맛집", "활기"],
        "description": "오키나와의 부엌. 생선·야채 구입 후 2층에서 즉석 요리 제공.",
        "cover_image": unsplash("photo-1542838132-92c53300491e"),
        "rating": 4.2, "review_count": 4500, "price_level": 1,
        "popularity_score": 80.0,
    }),
    ("seed:okinawa:nirai-kanai-bridge", {
        "country": "JP", "city": "okinawa", "region": "남부",
        "name": "니라이카나이 브리지", "name_en": "Nirai Kanai Bridge",
        "address": "Chinen, Nanjo City, Okinawa",
        "latitude": 26.1415, "longitude": 127.7985,
        "category": "photospot", "vibe_tags": ["뷰포인트", "드라이브", "자연"],
        "description": "언덕에서 내려오는 곡선 다리와 바다의 파노라마 뷰. 드라이브 명소.",
        "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
        "rating": 4.5, "review_count": 3800, "price_level": 1,
        "popularity_score": 83.0, "women_friendly": True,
    }),
    ("seed:okinawa:ukishima-garden", {
        "country": "JP", "city": "okinawa", "region": "나하",
        "name": "우키시마 가든", "name_en": "Ukishima Garden",
        "address": "1-10-10 Tsuboya, Naha City",
        "latitude": 26.2096, "longitude": 127.6882,
        "category": "cafe", "vibe_tags": ["비건", "힐링", "감성"],
        "description": "류큐 전통 가옥을 개조한 비건 카페 겸 갤러리. 채식 류큐 요리.",
        "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
        "rating": 4.5, "review_count": 1200, "price_level": 2,
        "popularity_score": 74.0, "women_friendly": True,
    }),
    ("seed:okinawa:kouri-island", {
        "country": "JP", "city": "okinawa", "region": "나키진",
        "name": "코우리 섬", "name_en": "Kouri Island",
        "address": "Kouri, Nakijin-son, Kunigami-gun",
        "latitude": 26.7118, "longitude": 127.9388,
        "category": "nature", "vibe_tags": ["바다", "힐링", "자연"],
        "description": "오키나와 사랑의 섬. 다리로 연결된 투명 바다. 하트락 포토 스폿.",
        "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
        "rating": 4.6, "review_count": 6200, "price_level": 1,
        "popularity_score": 88.0, "women_friendly": True,
    }),
]
