"""오사카 큐레이션 시드 (12곳)."""

from .helpers import unsplash

OSAKA_SEED: list[tuple[str, dict]] = [
    (
        "seed:osaka:dotonbori-glico",
        {
            "country": "JP",
            "city": "osaka",
            "region": "도톤보리",
            "name": "도톤보리 글리코 사인",
            "name_en": "Glico Sign",
            "address": "1 Chome-10 Dotonbori, Chuo Ward, Osaka",
            "latitude": 34.6687,
            "longitude": 135.5012,
            "category": "photospot",
            "vibe_tags": ["야경", "활기", "인스타"],
            "description": "오사카 인증샷 1순위. 강변에서 야경 베스트.",
            "cover_image": unsplash("photo-1590559899731-a382839e5549"),
            "instagram_hashtag": "#dotonbori",
            "rating": 4.5,
            "review_count": 18000,
            "popularity_score": 97.0,
            "safety_score": 5,
        },
    ),
    (
        "seed:osaka:osaka-castle",
        {
            "country": "JP",
            "city": "osaka",
            "region": "오사카성",
            "name": "오사카성",
            "name_en": "Osaka Castle",
            "address": "1-1 Osakajo, Chuo Ward, Osaka",
            "latitude": 34.6873,
            "longitude": 135.5262,
            "category": "photospot",
            "vibe_tags": ["분위기", "레트로"],
            "description": "도요토미 히데요시의 천수각. 봄 벚꽃 명소.",
            "cover_image": unsplash("photo-1590559899731-a382839e5549"),
            "instagram_hashtag": "#osakacastle",
            "rating": 4.5,
            "review_count": 25000,
            "price_level": 2,
            "popularity_score": 91.0,
            "safety_score": 5,
        },
    ),
    (
        "seed:osaka:umeda-sky",
        {
            "country": "JP",
            "city": "osaka",
            "region": "우메다",
            "name": "우메다 스카이 빌딩",
            "name_en": "Umeda Sky Building",
            "address": "1-1-88 Oyodonaka, Kita Ward, Osaka",
            "latitude": 34.7050,
            "longitude": 135.4900,
            "category": "photospot",
            "vibe_tags": ["야경", "모던", "인스타"],
            "description": "공중 정원 전망대. 360도 야경.",
            "cover_image": unsplash("photo-1480796927426-f609979314bd"),
            "instagram_hashtag": "#umedasky",
            "rating": 4.4,
            "review_count": 7200,
            "price_level": 2,
            "popularity_score": 83.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:osaka:cafe-naka-no-shima",
        {
            "country": "JP",
            "city": "osaka",
            "region": "나카노시마",
            "name": "그래프 카페",
            "name_en": "graf",
            "address": "Nakanoshima 4-1-9, Kita Ward, Osaka",
            "latitude": 34.6940,
            "longitude": 135.4894,
            "category": "cafe",
            "vibe_tags": ["모던", "조용", "감성"],
            "description": "디자인 스튜디오가 운영하는 미니멀 카페.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "instagram_hashtag": "#grafosaka",
            "rating": 4.4,
            "review_count": 620,
            "price_level": 2,
            "popularity_score": 70.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:osaka:lilo-coffee",
        {
            "country": "JP",
            "city": "osaka",
            "region": "신사이바시",
            "name": "리로 커피 로스터스",
            "name_en": "LiLo Coffee Roasters",
            "address": "1 Chome-10-28 Nishishinsaibashi, Chuo Ward, Osaka",
            "latitude": 34.6720,
            "longitude": 135.4988,
            "category": "cafe",
            "vibe_tags": ["감성", "모던"],
            "description": "오사카 스페셜티 커피 대표. 라떼아트 강함.",
            "cover_image": unsplash("photo-1495474472287-4d71bcdd2085"),
            "instagram_hashtag": "#lilocoffee",
            "rating": 4.6,
            "review_count": 950,
            "price_level": 2,
            "popularity_score": 78.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:osaka:pablo-cheesecake",
        {
            "country": "JP",
            "city": "osaka",
            "region": "신사이바시",
            "name": "파블로 치즈케이크",
            "name_en": "PABLO Shinsaibashi",
            "address": "3 Chome-7-28 Shinsaibashisuji, Chuo Ward, Osaka",
            "latitude": 34.6720,
            "longitude": 135.5012,
            "category": "dessert",
            "vibe_tags": ["감성", "인스타"],
            "description": "겉바속촉 미디엄 치즈케이크 본점.",
            "cover_image": unsplash("photo-1565958011703-44f9829ba187"),
            "instagram_hashtag": "#pablocheesecake",
            "rating": 4.3,
            "review_count": 4800,
            "price_level": 2,
            "popularity_score": 81.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:osaka:kuromon-market",
        {
            "country": "JP",
            "city": "osaka",
            "region": "닛폰바시",
            "name": "쿠로몬 시장",
            "name_en": "Kuromon Ichiba Market",
            "address": "2 Chome-4-1 Nipponbashi, Chuo Ward, Osaka",
            "latitude": 34.6657,
            "longitude": 135.5066,
            "category": "shopping",
            "vibe_tags": ["활기", "레트로"],
            "description": "오사카의 부엌. 해산물·과일·길거리 음식.",
            "cover_image": unsplash("photo-1604754742629-3e0498a8f4ee"),
            "instagram_hashtag": "#kuromonichiba",
            "rating": 4.3,
            "review_count": 8900,
            "price_level": 2,
            "popularity_score": 84.0,
        },
    ),
    (
        "seed:osaka:shinsaibashi-suji",
        {
            "country": "JP",
            "city": "osaka",
            "region": "신사이바시",
            "name": "신사이바시 스지 상점가",
            "name_en": "Shinsaibashi-suji Shopping Street",
            "address": "Shinsaibashisuji, Chuo Ward, Osaka",
            "latitude": 34.6748,
            "longitude": 135.5009,
            "category": "shopping",
            "vibe_tags": ["활기", "모던"],
            "description": "오사카 최대 쇼핑 아케이드. 면세 매장 다수.",
            "cover_image": unsplash("photo-1567721913486-6585f069b332"),
            "instagram_hashtag": "#shinsaibashi",
            "rating": 4.4,
            "review_count": 12000,
            "price_level": 2,
            "popularity_score": 88.0,
            "tax_free": True,
        },
    ),
    (
        "seed:osaka:takoyaki-wanaka",
        {
            "country": "JP",
            "city": "osaka",
            "region": "신사이바시",
            "name": "다코야키 와나카",
            "name_en": "Takoyaki Wanaka",
            "address": "1 Chome-1-13 Namba, Chuo Ward, Osaka",
            "latitude": 34.6671,
            "longitude": 135.5012,
            "category": "restaurant",
            "vibe_tags": ["가성비", "활기"],
            "description": "오사카 다코야키 명가. 줄 서서 먹는 길거리 명물.",
            "cover_image": unsplash("photo-1569718212165-3a8278d5f624"),
            "instagram_hashtag": "#takoyakiwanaka",
            "rating": 4.4,
            "review_count": 3800,
            "price_level": 1,
            "popularity_score": 85.0,
        },
    ),
    (
        "seed:osaka:ichiran-dotonbori",
        {
            "country": "JP",
            "city": "osaka",
            "region": "도톤보리",
            "name": "이치란 도톤보리점",
            "name_en": "Ichiran Dotonbori",
            "address": "7-18 Soemoncho, Chuo Ward, Osaka",
            "latitude": 34.6707,
            "longitude": 135.5014,
            "category": "restaurant",
            "vibe_tags": ["조용", "가성비"],
            "description": "도톤보리 한복판 1인 좌석 라멘.",
            "cover_image": unsplash("photo-1591814468924-caf88d1232e1"),
            "instagram_hashtag": "#ichiranosaka",
            "rating": 4.2,
            "review_count": 5200,
            "price_level": 2,
            "popularity_score": 79.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:osaka:tsuruhashi-fugetsu",
        {
            "country": "JP",
            "city": "osaka",
            "region": "도톤보리",
            "name": "후게츠 오코노미야키",
            "name_en": "Fugetsu Okonomiyaki",
            "address": "1 Chome-9-1 Dotonbori, Chuo Ward, Osaka",
            "latitude": 34.6681,
            "longitude": 135.5012,
            "category": "restaurant",
            "vibe_tags": ["활기", "가성비"],
            "description": "오사카 명물 오코노미야키. 본점 도톤보리.",
            "cover_image": unsplash("photo-1579871494447-9811cf80d66c"),
            "instagram_hashtag": "#fugetsu",
            "rating": 4.3,
            "review_count": 2900,
            "price_level": 2,
            "popularity_score": 77.0,
        },
    ),
    (
        "seed:osaka:nakanoshima-park",
        {
            "country": "JP",
            "city": "osaka",
            "region": "나카노시마",
            "name": "나카노시마 공원",
            "name_en": "Nakanoshima Park",
            "address": "Nakanoshima 1, Kita Ward, Osaka",
            "latitude": 34.6920,
            "longitude": 135.5022,
            "category": "nature",
            "vibe_tags": ["한적", "조용", "감성"],
            "description": "오사카 도심 강변 공원. 5월 장미 정원.",
            "cover_image": unsplash("photo-1490772888775-55fceea286b8"),
            "instagram_hashtag": "#nakanoshimapark",
            "rating": 4.5,
            "review_count": 2100,
            "popularity_score": 68.0,
            "women_friendly": True,
            "safety_score": 5,
        },
    ),
]
