"""삿포로 큐레이션 시드 (12곳)."""

from .helpers import unsplash

SAPPORO_SEED: list[tuple[str, dict]] = [
    (
        "seed:sapporo:odori-park",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "오도리",
            "name": "오도리 공원",
            "name_en": "Odori Park",
            "address": "Odori Nishi, Chuo Ward, Sapporo",
            "latitude": 43.0594,
            "longitude": 141.3536,
            "category": "nature",
            "vibe_tags": ["힐링", "자연", "활기"],
            "description": "삿포로 중심부를 가로지르는 1.5km 공원. 눈축제·맥주축제 메인 회장.",
            "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
            "rating": 4.4,
            "review_count": 9800,
            "price_level": 1,
            "popularity_score": 90.0,
            "women_friendly": True,
            "safety_score": 5,
        },
    ),
    (
        "seed:sapporo:clock-tower",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "중심가",
            "name": "삿포로 시계탑",
            "name_en": "Sapporo Clock Tower",
            "address": "Nishi 2-chome Kita 1-jo, Chuo Ward, Sapporo",
            "latitude": 43.0628,
            "longitude": 141.3538,
            "category": "culture",
            "vibe_tags": ["역사", "포토"],
            "description": "삿포로의 상징. 홋카이도 개척 시대인 1878년 건립.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 3.8,
            "review_count": 6700,
            "price_level": 1,
            "popularity_score": 80.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:sapporo:moerenuma-park",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "히가시구",
            "name": "모에레누마 공원",
            "name_en": "Moerenuma Park",
            "address": "1-1 Moere, Higashi Ward, Sapporo",
            "latitude": 43.1148,
            "longitude": 141.4258,
            "category": "nature",
            "vibe_tags": ["힐링", "자연", "예술"],
            "description": "이사무 노구치 설계 조각 공원. 유리 피라미드와 분수가 인상적.",
            "cover_image": unsplash("photo-1476820865390-c52aeebb9891"),
            "rating": 4.6,
            "review_count": 3200,
            "price_level": 1,
            "popularity_score": 82.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:sapporo:ramen-yokocho",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "스스키노",
            "name": "삿포로 라멘 요코초",
            "name_en": "Sapporo Ramen Yokocho",
            "address": "Minami 5-jo Nishi 3-chome, Chuo Ward, Sapporo",
            "latitude": 43.0545,
            "longitude": 141.3553,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌", "야간"],
            "description": "좁은 골목에 17개 라멘 가게 집결. 삿포로 미소라멘의 성지.",
            "cover_image": unsplash("photo-1569718212165-3a8278d5f624"),
            "rating": 4.3,
            "review_count": 5400,
            "price_level": 1,
            "popularity_score": 88.0,
        },
    ),
    (
        "seed:sapporo:nikka-whisky-yoichi",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "요이치",
            "name": "닛카 위스키 요이치 증류소",
            "name_en": "Nikka Whisky Yoichi Distillery",
            "address": "7-6 Kurokawa-cho, Yoichi-cho, Yoichi-gun, Hokkaido",
            "latitude": 43.1950,
            "longitude": 140.7888,
            "category": "culture",
            "vibe_tags": ["역사", "맛집", "조용"],
            "description": "마사타카 타케츠루 창업. 드라마 <맛상> 배경. 무료 시음·증류소 견학.",
            "cover_image": unsplash("photo-1514362545857-3bc16c4c7d1b"),
            "rating": 4.7,
            "review_count": 2900,
            "price_level": 1,
            "popularity_score": 84.0,
        },
    ),
    (
        "seed:sapporo:hokkaido-shrine",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "마루야마",
            "name": "홋카이도 신궁",
            "name_en": "Hokkaido Shrine",
            "address": "474 Miyagaoka, Chuo Ward, Sapporo",
            "latitude": 43.0572,
            "longitude": 141.3188,
            "category": "culture",
            "vibe_tags": ["영적", "자연", "조용"],
            "description": "마루야마 공원 안에 자리한 홋카이도 최대 신사. 벚꽃 명소.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.4,
            "review_count": 4200,
            "price_level": 1,
            "popularity_score": 83.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:sapporo:shiroi-koibito-park",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "니시구",
            "name": "시로이코이비토 파크",
            "name_en": "Shiroi Koibito Park",
            "address": "2-11-36 Miyanosawa, Nishi Ward, Sapporo",
            "latitude": 43.0706,
            "longitude": 141.2978,
            "category": "cafe",
            "vibe_tags": ["감성", "디저트", "활기"],
            "description": "홋카이도 명물 과자 '시로이코이비토' 공장+테마파크. 카페·견학 가능.",
            "cover_image": unsplash("photo-1558303982-f8f6d2d3e4ee"),
            "rating": 4.2,
            "review_count": 6500,
            "price_level": 2,
            "popularity_score": 85.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:sapporo:susukino-nightlife",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "스스키노",
            "name": "스스키노 유흥가",
            "name_en": "Susukino District",
            "address": "Susukino, Chuo Ward, Sapporo",
            "latitude": 43.0548,
            "longitude": 141.3560,
            "category": "bar",
            "vibe_tags": ["야간", "활기", "현지느낌"],
            "description": "도쿄 신주쿠에 버금가는 북일본 최대 환락가. 이자카야·스낵바 밀집.",
            "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
            "rating": 4.0,
            "review_count": 4800,
            "price_level": 2,
            "popularity_score": 80.0,
        },
    ),
    (
        "seed:sapporo:jozankei-onsen",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "조잔케이",
            "name": "조잔케이 온천",
            "name_en": "Jozankei Onsen",
            "address": "Jozankei, Minami Ward, Sapporo",
            "latitude": 42.9778,
            "longitude": 141.1293,
            "category": "hotel",
            "vibe_tags": ["힐링", "자연", "온천"],
            "description": "삿포로 시내에서 1시간. 계곡을 품은 리조트 온천. 단풍·설경 명소.",
            "cover_image": unsplash("photo-1500534314209-a25ddb2bd429"),
            "rating": 4.5,
            "review_count": 5100,
            "price_level": 3,
            "popularity_score": 87.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:sapporo:nijo-market",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "중심가",
            "name": "니조 시장",
            "name_en": "Nijo Market",
            "address": "Nijo, Chuo Ward, Sapporo",
            "latitude": 43.0596,
            "longitude": 141.3577,
            "category": "shopping",
            "vibe_tags": ["현지느낌", "맛집", "활기"],
            "description": "삿포로 중심부 재래시장. 홋카이도 해산물 덮밥과 게 요리로 유명.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.2,
            "review_count": 3900,
            "price_level": 2,
            "popularity_score": 78.0,
        },
    ),
    (
        "seed:sapporo:mt-moiwa",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "미나미구",
            "name": "모이와 산 전망대",
            "name_en": "Mt. Moiwa Observation Deck",
            "address": "Moiwa-yama, Minami Ward, Sapporo",
            "latitude": 43.0267,
            "longitude": 141.3128,
            "category": "photospot",
            "vibe_tags": ["뷰포인트", "야간", "힐링"],
            "description": "삿포로 야경 최고 명소. 로프웨이+미니케이블카로 정상 접근.",
            "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
            "rating": 4.5,
            "review_count": 4700,
            "price_level": 2,
            "popularity_score": 86.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:sapporo:soup-curry-garaku",
        {
            "country": "JP",
            "city": "sapporo",
            "region": "스스키노",
            "name": "수프 카레 가라쿠",
            "name_en": "Soup Curry Garaku",
            "address": "Minami 2-jo Nishi 2-chome, Chuo Ward, Sapporo",
            "latitude": 43.0560,
            "longitude": 141.3545,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌"],
            "description": "삿포로 발명 요리 '수프 카레' 명가. 홋카이도 채소 듬뿍.",
            "cover_image": unsplash("photo-1574484284002-952d92456975"),
            "rating": 4.6,
            "review_count": 3600,
            "price_level": 2,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
]
