"""서울 큐레이션 시드 (18곳)."""
from .helpers import unsplash

SEOUL_SEED: list[tuple[str, dict]] = [
    # ── 카페 ──
    ("seed:seoul:onion-anguk", {
        "country": "KR", "city": "seoul", "region": "안국",
        "name": "어니언 안국", "name_en": "Onion Anguk",
        "address": "서울 종로구 계동길 5",
        "latitude": 37.5762, "longitude": 126.9856,
        "category": "cafe", "vibe_tags": ["빈티지", "감성", "한적"],
        "description": "한옥을 개조한 베이커리 카페. 안국역 도보 5분.",
        "cover_image": unsplash("photo-1554118811-1e0d58224f24"),
        "instagram_hashtag": "#어니언안국", "rating": 4.5, "review_count": 6700,
        "price_level": 2, "popularity_score": 91.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:seoul:onion-seongsu", {
        "country": "KR", "city": "seoul", "region": "성수",
        "name": "어니언 성수", "name_en": "Onion Seongsu",
        "address": "서울 성동구 아차산로9길 8",
        "latitude": 37.5446, "longitude": 127.0556,
        "category": "cafe", "vibe_tags": ["빈티지", "감성", "활기"],
        "description": "철공소를 개조한 베이커리 카페. 성수 핫플의 시작.",
        "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
        "instagram_hashtag": "#어니언성수", "rating": 4.5, "review_count": 8900,
        "price_level": 2, "popularity_score": 93.0, "women_friendly": True,
    }),
    ("seed:seoul:cafe-onion-mia", {
        "country": "KR", "city": "seoul", "region": "미아",
        "name": "어니언 미아", "name_en": "Onion Mia",
        "address": "서울 강북구 도봉로11길 17",
        "latitude": 37.6260, "longitude": 127.0244,
        "category": "cafe", "vibe_tags": ["빈티지", "한적"],
        "description": "녹지를 품은 한옥 카페. 한적함을 원할 때.",
        "cover_image": unsplash("photo-1495474472287-4d71bcdd2085"),
        "instagram_hashtag": "#어니언미아", "rating": 4.4, "review_count": 1900,
        "price_level": 2, "popularity_score": 72.0, "women_friendly": True,
    }),
    ("seed:seoul:fritz-mapo", {
        "country": "KR", "city": "seoul", "region": "마포",
        "name": "프릳츠 도화", "name_en": "Fritz Coffee Company",
        "address": "서울 마포구 새창로2길 17",
        "latitude": 37.5408, "longitude": 126.9456,
        "category": "cafe", "vibe_tags": ["빈티지", "감성"],
        "description": "물개 로고 스페셜티 커피 브랜드 본점.",
        "cover_image": unsplash("photo-1521017432531-fbd92d768814"),
        "instagram_hashtag": "#fritzcoffee", "rating": 4.5, "review_count": 3200,
        "price_level": 2, "popularity_score": 80.0,
    }),
    ("seed:seoul:nudake-dosan", {
        "country": "KR", "city": "seoul", "region": "도산",
        "name": "누데이크 도산점", "name_en": "Nudake Dosan",
        "address": "서울 강남구 압구정로46길 50",
        "latitude": 37.5249, "longitude": 127.0392,
        "category": "dessert", "vibe_tags": ["모던", "인스타", "고급"],
        "description": "젠틀몬스터 자매 디저트. 페이스트리도 조형 작품.",
        "cover_image": unsplash("photo-1565958011703-44f9829ba187"),
        "instagram_hashtag": "#nudake", "rating": 4.4, "review_count": 4100,
        "price_level": 3, "popularity_score": 87.0, "women_friendly": True,
    }),
    ("seed:seoul:cafe-knotted-apgujeong", {
        "country": "KR", "city": "seoul", "region": "압구정",
        "name": "노티드 압구정 플래그십", "name_en": "Knotted Apgujeong",
        "address": "서울 강남구 압구정로 33",
        "latitude": 37.5275, "longitude": 127.0288,
        "category": "dessert", "vibe_tags": ["감성", "인스타"],
        "description": "도넛 마니아의 성지. 캐릭터 굿즈도 사랑받는다.",
        "cover_image": unsplash("photo-1567620905732-2d1ec7ab7445"),
        "instagram_hashtag": "#cafeknotted", "rating": 4.4, "review_count": 5600,
        "price_level": 2, "popularity_score": 85.0, "women_friendly": True,
    }),

    # ── 포토스팟 ──
    ("seed:seoul:ihwa-mural", {
        "country": "KR", "city": "seoul", "region": "이화동",
        "name": "이화벽화마을", "name_en": "Ihwa Mural Village",
        "address": "서울 종로구 이화장길",
        "latitude": 37.5790, "longitude": 127.0046,
        "category": "photospot", "vibe_tags": ["레트로", "한적", "감성"],
        "description": "낙산 자락 골목길 벽화. 도시 전망 명소.",
        "cover_image": unsplash("photo-1538485399081-7c8970e76d2c"),
        "instagram_hashtag": "#이화벽화마을", "rating": 4.2, "review_count": 2800,
        "popularity_score": 70.0, "safety_score": 4,
    }),
    ("seed:seoul:bukchon-hanok", {
        "country": "KR", "city": "seoul", "region": "북촌",
        "name": "북촌한옥마을", "name_en": "Bukchon Hanok Village",
        "address": "서울 종로구 계동길",
        "latitude": 37.5826, "longitude": 126.9831,
        "category": "photospot", "vibe_tags": ["레트로", "분위기", "감성"],
        "description": "경복궁·창덕궁 사이 한옥 골목. 한복 인생샷.",
        "cover_image": unsplash("photo-1583416750470-965b2707b355"),
        "instagram_hashtag": "#북촌한옥마을", "rating": 4.5, "review_count": 12000,
        "popularity_score": 89.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:seoul:lotte-tower-skydeck", {
        "country": "KR", "city": "seoul", "region": "잠실",
        "name": "롯데월드타워 서울스카이", "name_en": "Lotte World Tower Seoul Sky",
        "address": "서울 송파구 올림픽로 300",
        "latitude": 37.5126, "longitude": 127.1025,
        "category": "photospot", "vibe_tags": ["야경", "모던", "인스타"],
        "description": "118층 유리바닥. 서울 야경 한눈에.",
        "cover_image": unsplash("photo-1480796927426-f609979314bd"),
        "instagram_hashtag": "#서울스카이", "rating": 4.5, "review_count": 16000,
        "price_level": 3, "popularity_score": 88.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:seoul:n-seoul-tower", {
        "country": "KR", "city": "seoul", "region": "용산",
        "name": "N서울타워", "name_en": "N Seoul Tower",
        "address": "서울 용산구 남산공원길 105",
        "latitude": 37.5512, "longitude": 126.9882,
        "category": "photospot", "vibe_tags": ["야경", "분위기"],
        "description": "남산 정상의 서울 랜드마크. 케이블카로 접근.",
        "cover_image": unsplash("photo-1536098561742-ca998e48cbcc"),
        "instagram_hashtag": "#nseoultower", "rating": 4.5, "review_count": 24000,
        "price_level": 2, "popularity_score": 91.0, "safety_score": 5,
    }),
    ("seed:seoul:cheonggyecheon", {
        "country": "KR", "city": "seoul", "region": "종로",
        "name": "청계천", "name_en": "Cheonggyecheon",
        "address": "서울 종로구 서린동",
        "latitude": 37.5694, "longitude": 126.9787,
        "category": "photospot", "vibe_tags": ["한적", "야경"],
        "description": "도심 속 산책로. 야간 점등 시 야경 명소.",
        "cover_image": unsplash("photo-1554188248-986adbb73be4"),
        "instagram_hashtag": "#청계천", "rating": 4.4, "review_count": 9800,
        "popularity_score": 78.0, "women_friendly": True, "safety_score": 5,
    }),

    # ── 쇼핑 ──
    ("seed:seoul:starfield-coex", {
        "country": "KR", "city": "seoul", "region": "삼성동",
        "name": "스타필드 코엑스몰", "name_en": "Starfield COEX Mall",
        "address": "서울 강남구 영동대로 513",
        "latitude": 37.5126, "longitude": 127.0590,
        "category": "shopping", "vibe_tags": ["모던", "활기"],
        "description": "별마당 도서관으로 유명한 대형 지하 쇼핑몰.",
        "cover_image": unsplash("photo-1581235720704-06d3acfcb36f"),
        "instagram_hashtag": "#starfieldcoex", "rating": 4.4, "review_count": 14500,
        "price_level": 3, "popularity_score": 88.0, "tax_free": True, "safety_score": 5,
    }),
    ("seed:seoul:seongsu-yeonbang", {
        "country": "KR", "city": "seoul", "region": "성수",
        "name": "성수연방", "name_en": "Seongsu Yeonbang",
        "address": "서울 성동구 성수이로14길 14",
        "latitude": 37.5444, "longitude": 127.0560,
        "category": "shopping", "vibe_tags": ["빈티지", "감성", "모던"],
        "description": "공장을 개조한 복합 문화 공간. 편집숍·전시·카페.",
        "cover_image": unsplash("photo-1604754742629-3e0498a8f4ee"),
        "instagram_hashtag": "#성수연방", "rating": 4.4, "review_count": 3100,
        "popularity_score": 79.0, "women_friendly": True,
    }),
    ("seed:seoul:dongdaemun-ddp", {
        "country": "KR", "city": "seoul", "region": "동대문",
        "name": "동대문 디자인 플라자 (DDP)", "name_en": "Dongdaemun Design Plaza",
        "address": "서울 중구 을지로 281",
        "latitude": 37.5670, "longitude": 127.0095,
        "category": "shopping", "vibe_tags": ["모던", "야경", "인스타"],
        "description": "자하 하디드 설계 곡선 건축물. 야간 LED 장미밭 명소.",
        "cover_image": unsplash("photo-1505740420928-5e560c06d30e"),
        "instagram_hashtag": "#ddp", "rating": 4.4, "review_count": 11000,
        "popularity_score": 82.0, "tax_free": True,
    }),

    # ── 식당 ──
    ("seed:seoul:gwangjang-yukhoe", {
        "country": "KR", "city": "seoul", "region": "종로",
        "name": "광장시장 육회골목", "name_en": "Gwangjang Market Yukhoe Alley",
        "address": "서울 종로구 창경궁로 88",
        "latitude": 37.5701, "longitude": 126.9999,
        "category": "restaurant", "vibe_tags": ["레트로", "활기", "가성비"],
        "description": "전·육회·마약김밥. 한국 시장 음식의 백과사전.",
        "cover_image": unsplash("photo-1604754742629-3e0498a8f4ee"),
        "instagram_hashtag": "#광장시장", "rating": 4.3, "review_count": 13000,
        "price_level": 2, "popularity_score": 86.0,
    }),
    ("seed:seoul:tosokchon-samgye", {
        "country": "KR", "city": "seoul", "region": "경복궁",
        "name": "토속촌 삼계탕", "name_en": "Tosokchon Samgyetang",
        "address": "서울 종로구 자하문로5길 5",
        "latitude": 37.5779, "longitude": 126.9712,
        "category": "restaurant", "vibe_tags": ["레트로", "분위기"],
        "description": "역대 대통령들이 다녀간 삼계탕 명가.",
        "cover_image": unsplash("photo-1591814468924-caf88d1232e1"),
        "instagram_hashtag": "#토속촌", "rating": 4.3, "review_count": 8400,
        "price_level": 2, "popularity_score": 80.0,
    }),

    # ── 자연 ──
    ("seed:seoul:seokchon-lake", {
        "country": "KR", "city": "seoul", "region": "잠실",
        "name": "석촌호수", "name_en": "Seokchon Lake",
        "address": "서울 송파구 잠실동",
        "latitude": 37.5089, "longitude": 127.0987,
        "category": "nature", "vibe_tags": ["한적", "감성", "야경"],
        "description": "롯데월드 옆 호숫가 산책로. 봄 벚꽃 명소.",
        "cover_image": unsplash("photo-1490772888775-55fceea286b8"),
        "instagram_hashtag": "#석촌호수", "rating": 4.5, "review_count": 6900,
        "popularity_score": 76.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:seoul:han-river-yeouido", {
        "country": "KR", "city": "seoul", "region": "여의도",
        "name": "여의도 한강공원", "name_en": "Yeouido Hangang Park",
        "address": "서울 영등포구 여의동로 330",
        "latitude": 37.5283, "longitude": 126.9335,
        "category": "nature", "vibe_tags": ["한적", "야경", "활기"],
        "description": "한강 자전거·치맥의 성지. 야경과 불꽃축제 명소.",
        "cover_image": unsplash("photo-1490772888775-55fceea286b8"),
        "instagram_hashtag": "#여의도한강공원", "rating": 4.6, "review_count": 18000,
        "popularity_score": 85.0, "women_friendly": True, "safety_score": 5,
    }),
]
