"""동남아시아 도시 큐레이션 시드 — 방콕·발리·싱가포르·하노이·호치민·쿠알라룸푸르."""

from .helpers import unsplash

# ─── 방콕 (8곳) ──────────────────────────────────────────────────────────────
BANGKOK_SEED: list[tuple[str, dict]] = [
    (
        "seed:bangkok:grand-palace",
        {
            "country": "TH",
            "city": "bangkok",
            "region": "프라나콘",
            "name": "왕궁 & 에메랄드 불상",
            "name_en": "Grand Palace & Wat Phra Kaew",
            "address": "Na Phra Lan Rd, Phra Borom Maha Ratchawang, Phra Nakhon, Bangkok",
            "latitude": 13.7499,
            "longitude": 100.4914,
            "category": "culture",
            "vibe_tags": ["역사", "영적", "전통"],
            "description": "태국 왕실 건축의 정수. 에메랄드 불상 봉안 사원. 드레스코드 필수.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.6,
            "review_count": 42000,
            "price_level": 2,
            "popularity_score": 97.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:bangkok:chatuchak-market",
        {
            "country": "TH",
            "city": "bangkok",
            "region": "짜뚜짝",
            "name": "짜뚜짝 주말시장",
            "name_en": "Chatuchak Weekend Market",
            "address": "587/10 Kamphaeng Phet 2 Rd, Chatuchak, Bangkok",
            "latitude": 13.7999,
            "longitude": 100.5500,
            "category": "shopping",
            "vibe_tags": ["활기", "현지느낌", "맛집"],
            "description": "세계 최대 주말시장. 8000개 이상 노점. 골동품·의류·음식 천국.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.4,
            "review_count": 28000,
            "price_level": 1,
            "popularity_score": 92.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bangkok:khao-san-road",
        {
            "country": "TH",
            "city": "bangkok",
            "region": "반람푸",
            "name": "카오산 로드",
            "name_en": "Khao San Road",
            "address": "Khao San Road, Talat Yot, Phra Nakhon, Bangkok",
            "latitude": 13.7589,
            "longitude": 100.4969,
            "category": "bar",
            "vibe_tags": ["야간", "활기", "배낭여행"],
            "description": "배낭여행자의 성지. 저렴한 숙소·음식·야간 파티가 24시간 이어짐.",
            "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
            "rating": 4.1,
            "review_count": 19000,
            "price_level": 1,
            "popularity_score": 88.0,
        },
    ),
    (
        "seed:bangkok:wat-arun",
        {
            "country": "TH",
            "city": "bangkok",
            "region": "방콕 야이",
            "name": "왓 아룬 (새벽 사원)",
            "name_en": "Wat Arun",
            "address": "158 Thanon Wang Doem, Wat Arun, Bangkok Yai, Bangkok",
            "latitude": 13.7436,
            "longitude": 100.4889,
            "category": "culture",
            "vibe_tags": ["역사", "영적", "포토"],
            "description": "차오프라야 강변 도자기 장식 불탑. 해질녘 조명이 환상적.",
            "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
            "rating": 4.5,
            "review_count": 31000,
            "price_level": 1,
            "popularity_score": 93.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bangkok:street-food-yaowarat",
        {
            "country": "TH",
            "city": "bangkok",
            "region": "야오와랏",
            "name": "야오와랏 차이나타운 야시장",
            "name_en": "Yaowarat Chinatown Night Market",
            "address": "Yaowarat Rd, Samphanthawong, Bangkok",
            "latitude": 13.7400,
            "longitude": 100.5122,
            "category": "restaurant",
            "vibe_tags": ["맛집", "야간", "현지느낌"],
            "description": "방콕 최고 야시장 거리. 팟타이·딤섬·두리안·제비집 요리 집결.",
            "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
            "rating": 4.5,
            "review_count": 24000,
            "price_level": 1,
            "popularity_score": 92.0,
        },
    ),
    (
        "seed:bangkok:asiatique",
        {
            "country": "TH",
            "city": "bangkok",
            "region": "차론낙혼",
            "name": "아시아티크 더 리버프론트",
            "name_en": "Asiatique The Riverfront",
            "address": "2194 Charoen Krung Rd, Wat Phraya Krai, Bang Kho Laem, Bangkok",
            "latitude": 13.7197,
            "longitude": 100.5082,
            "category": "shopping",
            "vibe_tags": ["야간", "감성", "활기"],
            "description": "창고를 개조한 리버사이드 나이트마켓. 대관람차·레스토랑·공연.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.3,
            "review_count": 16000,
            "price_level": 2,
            "popularity_score": 85.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bangkok:icon-siam",
        {
            "country": "TH",
            "city": "bangkok",
            "region": "클롱산",
            "name": "아이콘 시암",
            "name_en": "ICONSIAM",
            "address": "299 Charoen Nakhon Soi 5, Khlong San, Bangkok",
            "latitude": 13.7266,
            "longitude": 100.5093,
            "category": "shopping",
            "vibe_tags": ["고급", "모던", "활기"],
            "description": "2019년 오픈 최고급 쇼핑몰. 실내 수상시장·루프탑 수영장·명품관.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.4,
            "review_count": 21000,
            "price_level": 3,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bangkok:lumphini-park",
        {
            "country": "TH",
            "city": "bangkok",
            "region": "파토움완",
            "name": "룸피니 공원",
            "name_en": "Lumpini Park",
            "address": "Rama IV Rd, Lumphini, Pathum Wan, Bangkok",
            "latitude": 13.7308,
            "longitude": 100.5418,
            "category": "nature",
            "vibe_tags": ["힐링", "자연", "조용"],
            "description": "방콕의 허파. 도심 속 大湖와 녹음. 아침 태극권·조정·모니터 도마뱀.",
            "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
            "rating": 4.3,
            "review_count": 12000,
            "price_level": 1,
            "popularity_score": 82.0,
            "women_friendly": True,
        },
    ),
]

# ─── 발리 (8곳) ──────────────────────────────────────────────────────────────
BALI_SEED: list[tuple[str, dict]] = [
    (
        "seed:bali:tanah-lot",
        {
            "country": "ID",
            "city": "bali",
            "region": "타바난",
            "name": "따나 롯 사원",
            "name_en": "Tanah Lot Temple",
            "address": "Beraban, Kediri, Tabanan Regency, Bali",
            "latitude": -8.6211,
            "longitude": 115.0865,
            "category": "culture",
            "vibe_tags": ["영적", "자연", "일몰"],
            "description": "바다 위 바위 섬에 세워진 힌두 사원. 일몰 포토 성지.",
            "cover_image": unsplash("photo-1537996194471-e657df975ab4"),
            "rating": 4.6,
            "review_count": 38000,
            "price_level": 2,
            "popularity_score": 96.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:bali:ubud-rice-terraces",
        {
            "country": "ID",
            "city": "bali",
            "region": "우붓",
            "name": "우붓 떼갈랄랑 계단논",
            "name_en": "Tegallalang Rice Terraces",
            "address": "Tegallalang, Gianyar, Bali",
            "latitude": -8.4332,
            "longitude": 115.2797,
            "category": "nature",
            "vibe_tags": ["자연", "힐링", "포토"],
            "description": "유네스코 세계유산 발리 물 관개 문화(수박) 계단논. 새벽 안개 장관.",
            "cover_image": unsplash("photo-1537996194471-e657df975ab4"),
            "rating": 4.5,
            "review_count": 22000,
            "price_level": 1,
            "popularity_score": 92.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bali:kuta-beach",
        {
            "country": "ID",
            "city": "bali",
            "region": "쿠타",
            "name": "쿠타 비치",
            "name_en": "Kuta Beach",
            "address": "Kuta, Badung Regency, Bali",
            "latitude": -8.7184,
            "longitude": 115.1686,
            "category": "nature",
            "vibe_tags": ["바다", "서핑", "활기"],
            "description": "발리 서핑 메카. 초보자 서핑 레슨 천국. 일몰 시간대 파티 분위기.",
            "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
            "rating": 4.2,
            "review_count": 31000,
            "price_level": 1,
            "popularity_score": 90.0,
        },
    ),
    (
        "seed:bali:seminyak-cafe",
        {
            "country": "ID",
            "city": "bali",
            "region": "스미냑",
            "name": "스미냑 카페 & 부티크 거리",
            "name_en": "Seminyak Cafe Strip",
            "address": "Seminyak, Kuta, Badung Regency, Bali",
            "latitude": -8.6908,
            "longitude": 115.1622,
            "category": "cafe",
            "vibe_tags": ["고급", "감성", "트렌디"],
            "description": "인피니티풀 카페·부티크 호텔·레스토랑 밀집. 발리 힙스터 베이스.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "rating": 4.4,
            "review_count": 15000,
            "price_level": 3,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bali:sacred-monkey-ubud",
        {
            "country": "ID",
            "city": "bali",
            "region": "우붓",
            "name": "우붓 신성한 원숭이 숲",
            "name_en": "Sacred Monkey Forest Ubud",
            "address": "Jl. Monkey Forest, Ubud, Gianyar, Bali",
            "latitude": -8.5192,
            "longitude": 115.2586,
            "category": "nature",
            "vibe_tags": ["자연", "활기", "힐링"],
            "description": "600마리 원숭이와 힌두 사원 공존하는 원시림. 우붓 중심에서 도보 가능.",
            "cover_image": unsplash("photo-1537996194471-e657df975ab4"),
            "rating": 4.4,
            "review_count": 19000,
            "price_level": 1,
            "popularity_score": 87.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bali:nusa-penida",
        {
            "country": "ID",
            "city": "bali",
            "region": "누사 페니다",
            "name": "누사 페니다 섬",
            "name_en": "Nusa Penida Island",
            "address": "Nusa Penida, Klungkung, Bali",
            "latitude": -8.7275,
            "longitude": 115.5445,
            "category": "nature",
            "vibe_tags": ["바다", "자연", "힐링"],
            "description": "발리 페리 45분. 에인절빌라봉·케링킹비치 등 SNS 명소 집결 섬.",
            "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
            "rating": 4.7,
            "review_count": 14000,
            "price_level": 2,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bali:ubud-traditional-dance",
        {
            "country": "ID",
            "city": "bali",
            "region": "우붓",
            "name": "우붓 전통 댄스 공연",
            "name_en": "Ubud Traditional Dance",
            "address": "Jl. Raya Ubud, Ubud, Gianyar, Bali",
            "latitude": -8.5069,
            "longitude": 115.2624,
            "category": "culture",
            "vibe_tags": ["전통", "예술", "활기"],
            "description": "케짝·레공·바롱 댄스. 밤마다 열리는 발리 힌두 전통 공연.",
            "cover_image": unsplash("photo-1558618666-fcd25c85cd64"),
            "rating": 4.5,
            "review_count": 9800,
            "price_level": 2,
            "popularity_score": 85.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:bali:canggu-surf-cafe",
        {
            "country": "ID",
            "city": "bali",
            "region": "창구",
            "name": "창구 서퍼 카페",
            "name_en": "Canggu Surf & Cafe Scene",
            "address": "Canggu, North Kuta, Badung Regency, Bali",
            "latitude": -8.6478,
            "longitude": 115.1320,
            "category": "cafe",
            "vibe_tags": ["서핑", "트렌디", "힐링"],
            "description": "디지털 노마드·서퍼의 수도. 아사이볼·스무디볼·코코넛 라떼 카페 밀집.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "rating": 4.5,
            "review_count": 12000,
            "price_level": 2,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
]

# ─── 싱가포르 (8곳) ───────────────────────────────────────────────────────────
SINGAPORE_SEED: list[tuple[str, dict]] = [
    (
        "seed:singapore:gardens-by-the-bay",
        {
            "country": "SG",
            "city": "singapore",
            "region": "마리나",
            "name": "가든스 바이 더 베이",
            "name_en": "Gardens by the Bay",
            "address": "18 Marina Gardens Dr, Singapore 018953",
            "latitude": 1.2816,
            "longitude": 103.8636,
            "category": "nature",
            "vibe_tags": ["모던", "자연", "야간"],
            "description": "슈퍼트리 그로브 야간 조명쇼. 클라우드 포레스트·플라워 돔 온실.",
            "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
            "rating": 4.7,
            "review_count": 45000,
            "price_level": 2,
            "popularity_score": 97.0,
            "women_friendly": True,
            "safety_score": 5,
        },
    ),
    (
        "seed:singapore:marina-bay-sands",
        {
            "country": "SG",
            "city": "singapore",
            "region": "마리나",
            "name": "마리나 베이 샌즈",
            "name_en": "Marina Bay Sands",
            "address": "10 Bayfront Ave, Singapore 018956",
            "latitude": 1.2838,
            "longitude": 103.8607,
            "category": "hotel",
            "vibe_tags": ["고급", "모던", "야간"],
            "description": "3개 타워를 잇는 배 모양 루프탑 인피니티풀과 전망대. 싱가포르 랜드마크.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.5,
            "review_count": 38000,
            "price_level": 4,
            "popularity_score": 96.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:singapore:hawker-centre",
        {
            "country": "SG",
            "city": "singapore",
            "region": "차이나타운",
            "name": "맥스웰 호커센터",
            "name_en": "Maxwell Food Centre",
            "address": "1 Kadayanallur St, Singapore 069184",
            "latitude": 1.2802,
            "longitude": 103.8449,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌", "활기"],
            "description": "싱가포르 서민 음식 천국. 치킨라이스·락사·바쿠테 등 정통 현지 맛.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.4,
            "review_count": 22000,
            "price_level": 1,
            "popularity_score": 92.0,
        },
    ),
    (
        "seed:singapore:sentosa-island",
        {
            "country": "SG",
            "city": "singapore",
            "region": "센토사",
            "name": "센토사 섬",
            "name_en": "Sentosa Island",
            "address": "Sentosa, Singapore",
            "latitude": 1.2494,
            "longitude": 103.8303,
            "category": "nature",
            "vibe_tags": ["바다", "활기", "가족"],
            "description": "유니버설 스튜디오·USS·케이블카·해변이 공존하는 리조트 섬.",
            "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
            "rating": 4.3,
            "review_count": 28000,
            "price_level": 3,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:singapore:little-india",
        {
            "country": "SG",
            "city": "singapore",
            "region": "리틀 인디아",
            "name": "리틀 인디아",
            "name_en": "Little India",
            "address": "Little India, Singapore",
            "latitude": 1.3066,
            "longitude": 103.8518,
            "category": "culture",
            "vibe_tags": ["현지느낌", "활기", "역사"],
            "description": "타밀나두 문화권 집결지. 형형색색 힌두 사원·꽃시장·커리 맛집.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.3,
            "review_count": 15000,
            "price_level": 1,
            "popularity_score": 83.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:singapore:chinatown-sg",
        {
            "country": "SG",
            "city": "singapore",
            "region": "차이나타운",
            "name": "싱가포르 차이나타운",
            "name_en": "Chinatown Singapore",
            "address": "Chinatown, Singapore",
            "latitude": 1.2827,
            "longitude": 103.8441,
            "category": "shopping",
            "vibe_tags": ["현지느낌", "활기", "역사"],
            "description": "전통 숍하우스·야시장·저렴한 기념품. 불아사 방문 포함 추천.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.2,
            "review_count": 18000,
            "price_level": 1,
            "popularity_score": 85.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:singapore:orchard-road",
        {
            "country": "SG",
            "city": "singapore",
            "region": "오차드",
            "name": "오차드 로드",
            "name_en": "Orchard Road",
            "address": "Orchard Road, Singapore",
            "latitude": 1.3048,
            "longitude": 103.8318,
            "category": "shopping",
            "vibe_tags": ["고급", "트렌디", "모던"],
            "description": "싱가포르 최고급 쇼핑 거리. 아이온·파라곤·313@서머셋 백화점 밀집.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.2,
            "review_count": 25000,
            "price_level": 3,
            "popularity_score": 87.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:singapore:kampong-glam",
        {
            "country": "SG",
            "city": "singapore",
            "region": "캄퐁글람",
            "name": "캄퐁글람 & 하지레인",
            "name_en": "Kampong Glam & Haji Lane",
            "address": "Haji Lane, Kampong Glam, Singapore",
            "latitude": 1.3024,
            "longitude": 103.8596,
            "category": "shopping",
            "vibe_tags": ["감성", "트렌디", "포토"],
            "description": "말레이 문화·이슬람 건축·힙스터 카페 공존. 하지레인 벽화 포토존.",
            "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
            "rating": 4.4,
            "review_count": 13000,
            "price_level": 2,
            "popularity_score": 87.0,
            "women_friendly": True,
        },
    ),
]

# ─── 하노이 (6곳) ─────────────────────────────────────────────────────────────
HANOI_SEED: list[tuple[str, dict]] = [
    (
        "seed:hanoi:hoan-kiem-lake",
        {
            "country": "VN",
            "city": "hanoi",
            "region": "호안끼엠",
            "name": "호안끼엠 호수",
            "name_en": "Hoan Kiem Lake",
            "address": "Dinh Tien Hoang, Hoan Kiem District, Hanoi",
            "latitude": 21.0285,
            "longitude": 105.8542,
            "category": "nature",
            "vibe_tags": ["힐링", "자연", "활기"],
            "description": "하노이 심장부 도심 호수. 떠 거북이 전설·응옥썬 사원. 주말 보행자전용.",
            "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
            "rating": 4.4,
            "review_count": 21000,
            "price_level": 1,
            "popularity_score": 92.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:hanoi:old-quarter",
        {
            "country": "VN",
            "city": "hanoi",
            "region": "구시가지",
            "name": "하노이 구시가지 36거리",
            "name_en": "Hanoi Old Quarter",
            "address": "Old Quarter, Hoan Kiem District, Hanoi",
            "latitude": 21.0340,
            "longitude": 105.8492,
            "category": "culture",
            "vibe_tags": ["현지느낌", "활기", "역사"],
            "description": "1000년 역사의 길드 거리. 품목별 거리(실크·종이·철물). 에그커피 발원지.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.5,
            "review_count": 18000,
            "price_level": 1,
            "popularity_score": 92.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:hanoi:egg-coffee",
        {
            "country": "VN",
            "city": "hanoi",
            "region": "호안끼엠",
            "name": "지앙 에그 커피",
            "name_en": "Giang Cafe (Egg Coffee)",
            "address": "39 Nguyen Huu Huan, Hoan Kiem District, Hanoi",
            "latitude": 21.0360,
            "longitude": 105.8530,
            "category": "cafe",
            "vibe_tags": ["현지느낌", "감성", "조용"],
            "description": "1946년 창업. 달걀노른자 거품으로 만든 하노이 명물 에그커피 원조.",
            "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
            "rating": 4.6,
            "review_count": 9800,
            "price_level": 1,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:hanoi:ho-chi-minh-mausoleum",
        {
            "country": "VN",
            "city": "hanoi",
            "region": "바딘",
            "name": "호찌민 묘소",
            "name_en": "Ho Chi Minh Mausoleum",
            "address": "2 Hung Vuong, Ba Dinh, Hanoi",
            "latitude": 21.0366,
            "longitude": 105.8344,
            "category": "culture",
            "vibe_tags": ["역사", "조용"],
            "description": "베트남 혁명 지도자 호찌민의 유리관 안치. 바딘 광장 주변 역사 지구.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.2,
            "review_count": 14000,
            "price_level": 1,
            "popularity_score": 83.0,
        },
    ),
    (
        "seed:hanoi:pho-gia-truyen",
        {
            "country": "VN",
            "city": "hanoi",
            "region": "구시가지",
            "name": "퍼 자 쭈옌 (포 원조)",
            "name_en": "Pho Gia Truyen",
            "address": "49 Bat Dan, Hoan Kiem District, Hanoi",
            "latitude": 21.0348,
            "longitude": 105.8468,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌"],
            "description": "100년 역사 하노이 쌀국수 원조. 연탄불 뼈육수 18시간 우림. 오전 중 매진.",
            "cover_image": unsplash("photo-1574484284002-952d92456975"),
            "rating": 4.6,
            "review_count": 12000,
            "price_level": 1,
            "popularity_score": 90.0,
        },
    ),
    (
        "seed:hanoi:train-street",
        {
            "country": "VN",
            "city": "hanoi",
            "region": "구시가지",
            "name": "하노이 기차 거리",
            "name_en": "Hanoi Train Street",
            "address": "Le Duan, Dong Da District, Hanoi",
            "latitude": 21.0268,
            "longitude": 105.8432,
            "category": "photospot",
            "vibe_tags": ["감성", "포토", "현지느낌"],
            "description": "민가 사이로 실제 기차가 지나가는 좁은 골목. 카페에서 기차 관람.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.3,
            "review_count": 16000,
            "price_level": 1,
            "popularity_score": 87.0,
            "women_friendly": True,
        },
    ),
]

# ─── 호치민 (6곳) ─────────────────────────────────────────────────────────────
HOCHIMINH_SEED: list[tuple[str, dict]] = [
    (
        "seed:hochiminh:ben-thanh-market",
        {
            "country": "VN",
            "city": "hochiminh",
            "region": "1군",
            "name": "벤탄 시장",
            "name_en": "Ben Thanh Market",
            "address": "Le Loi, Ben Thanh Ward, District 1, Ho Chi Minh City",
            "latitude": 10.7723,
            "longitude": 106.6980,
            "category": "shopping",
            "vibe_tags": ["활기", "현지느낌", "맛집"],
            "description": "호치민 상징 시장. 의류·향신료·먹거리. 야외 야시장 밤 10시까지.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.2,
            "review_count": 22000,
            "price_level": 1,
            "popularity_score": 90.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:hochiminh:war-remnants-museum",
        {
            "country": "VN",
            "city": "hochiminh",
            "region": "3군",
            "name": "전쟁박물관",
            "name_en": "War Remnants Museum",
            "address": "28 Vo Van Tan, Ward 6, District 3, Ho Chi Minh City",
            "latitude": 10.7798,
            "longitude": 106.6929,
            "category": "culture",
            "vibe_tags": ["역사", "교육", "조용"],
            "description": "베트남 전쟁 실상을 담은 사진·전투기·탱크 전시. 가장 많이 방문하는 박물관.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.5,
            "review_count": 31000,
            "price_level": 1,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:hochiminh:bui-vien-walking-street",
        {
            "country": "VN",
            "city": "hochiminh",
            "region": "1군",
            "name": "부이비엔 워킹 스트리트",
            "name_en": "Bui Vien Walking Street",
            "address": "Bui Vien, Pham Ngu Lao Ward, District 1, Ho Chi Minh City",
            "latitude": 10.7688,
            "longitude": 106.6935,
            "category": "bar",
            "vibe_tags": ["야간", "활기", "배낭여행"],
            "description": "동남아 최대 배낭여행자 거리. 맥주 1만동·라이브 음악·버거 24시간.",
            "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
            "rating": 4.1,
            "review_count": 19000,
            "price_level": 1,
            "popularity_score": 87.0,
        },
    ),
    (
        "seed:hochiminh:notre-dame-cathedral",
        {
            "country": "VN",
            "city": "hochiminh",
            "region": "1군",
            "name": "노트르담 성당",
            "name_en": "Notre-Dame Cathedral Basilica",
            "address": "1 Cong xa Paris, Ben Nghe Ward, District 1, Ho Chi Minh City",
            "latitude": 10.7797,
            "longitude": 106.6990,
            "category": "culture",
            "vibe_tags": ["역사", "포토"],
            "description": "1880년 프랑스 식민지 시절 건립. 붉은 벽돌 쌍탑 건물. 인기 포토 스폿.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.3,
            "review_count": 18000,
            "price_level": 1,
            "popularity_score": 85.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:hochiminh:pho-hoa-pasteur",
        {
            "country": "VN",
            "city": "hochiminh",
            "region": "3군",
            "name": "퍼 호아 파스퇴르",
            "name_en": "Pho Hoa Pasteur",
            "address": "260C Pasteur, Vo Thi Sau Ward, District 3, Ho Chi Minh City",
            "latitude": 10.7780,
            "longitude": 106.6888,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌"],
            "description": "60년 역사 호치민 최고 쌀국수 명가. 새벽 5시부터 현지인 줄 섬.",
            "cover_image": unsplash("photo-1574484284002-952d92456975"),
            "rating": 4.5,
            "review_count": 11000,
            "price_level": 1,
            "popularity_score": 88.0,
        },
    ),
    (
        "seed:hochiminh:cu-chi-tunnels",
        {
            "country": "VN",
            "city": "hochiminh",
            "region": "쿠찌",
            "name": "구찌 터널",
            "name_en": "Cu Chi Tunnels",
            "address": "Phu Hiep Hamlet, Phu My Hung, Cu Chi District, Ho Chi Minh City",
            "latitude": 11.1412,
            "longitude": 106.4649,
            "category": "culture",
            "vibe_tags": ["역사", "교육"],
            "description": "베트남전 게릴라 지하 터널 시스템. 실제 250km 중 일부 관광객 체험 개방.",
            "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
            "rating": 4.4,
            "review_count": 24000,
            "price_level": 2,
            "popularity_score": 87.0,
        },
    ),
]

# ─── 쿠알라룸푸르 (6곳) ──────────────────────────────────────────────────────
KUALA_LUMPUR_SEED: list[tuple[str, dict]] = [
    (
        "seed:kl:petronas-towers",
        {
            "country": "MY",
            "city": "kuala_lumpur",
            "region": "KLCC",
            "name": "페트로나스 트윈 타워",
            "name_en": "Petronas Twin Towers",
            "address": "Kuala Lumpur City Centre, 50088 Kuala Lumpur",
            "latitude": 3.1579,
            "longitude": 101.7120,
            "category": "photospot",
            "vibe_tags": ["모던", "야간", "뷰포인트"],
            "description": "세계 최고 쌍둥이 빌딩. 스카이브리지(41층) 전망대 예약 필수.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.6,
            "review_count": 42000,
            "price_level": 2,
            "popularity_score": 97.0,
            "women_friendly": True,
            "safety_score": 4,
        },
    ),
    (
        "seed:kl:batu-caves",
        {
            "country": "MY",
            "city": "kuala_lumpur",
            "region": "바투케이브",
            "name": "바투 동굴",
            "name_en": "Batu Caves",
            "address": "Gombak, 68100 Batu Caves, Selangor",
            "latitude": 3.2379,
            "longitude": 101.6840,
            "category": "culture",
            "vibe_tags": ["영적", "역사", "자연"],
            "description": "42m 황금 무루간 신상. 272개 계단 오르면 석회암 동굴 힌두 사원.",
            "cover_image": unsplash("photo-1580619305218-8423a7ef79b4"),
            "rating": 4.5,
            "review_count": 31000,
            "price_level": 1,
            "popularity_score": 92.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:kl:jalan-alor-food",
        {
            "country": "MY",
            "city": "kuala_lumpur",
            "region": "부킷빈탕",
            "name": "잘란 알로르 야시장",
            "name_en": "Jalan Alor Street Food",
            "address": "Jalan Alor, Bukit Bintang, Kuala Lumpur",
            "latitude": 3.1452,
            "longitude": 101.7078,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌", "야간"],
            "description": "KL 최고 야시장 음식 거리. 사테이·방쿠트·나시레막·로띠차나이 집결.",
            "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
            "rating": 4.4,
            "review_count": 22000,
            "price_level": 1,
            "popularity_score": 90.0,
        },
    ),
    (
        "seed:kl:central-market",
        {
            "country": "MY",
            "city": "kuala_lumpur",
            "region": "치나타운",
            "name": "센트럴 마켓 & 차이나타운",
            "name_en": "Central Market & Chinatown",
            "address": "Jalan Hang Kasturi, City Centre, Kuala Lumpur",
            "latitude": 3.1434,
            "longitude": 101.6969,
            "category": "shopping",
            "vibe_tags": ["현지느낌", "활기", "전통"],
            "description": "말레이 공예·배틱·페란칸 기념품. 근처 페탈링 차이나타운 야시장.",
            "cover_image": unsplash("photo-1542838132-92c53300491e"),
            "rating": 4.1,
            "review_count": 15000,
            "price_level": 1,
            "popularity_score": 80.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:kl:klcc-park",
        {
            "country": "MY",
            "city": "kuala_lumpur",
            "region": "KLCC",
            "name": "KLCC 공원 & 분수쇼",
            "name_en": "KLCC Park & Fountain Show",
            "address": "Jalan Ampang, 50450 Kuala Lumpur",
            "latitude": 3.1538,
            "longitude": 101.7118,
            "category": "nature",
            "vibe_tags": ["야간", "힐링", "활기"],
            "description": "페트로나스 타워 앞 공원. 매일 저녁 레이저·분수 쇼. 산책하기 좋음.",
            "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
            "rating": 4.5,
            "review_count": 19000,
            "price_level": 1,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:kl:menara-kl-tower",
        {
            "country": "MY",
            "city": "kuala_lumpur",
            "region": "부킷나나스",
            "name": "KL 타워 전망대",
            "name_en": "Menara KL Tower",
            "address": "2 Jalan Punchak, Off Jalan P Ramlee, Kuala Lumpur",
            "latitude": 3.1529,
            "longitude": 101.7034,
            "category": "photospot",
            "vibe_tags": ["뷰포인트", "야간", "모던"],
            "description": "421m 통신탑 전망대. 페트로나스 타워를 정면으로 바라보는 최고 각도.",
            "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
            "rating": 4.3,
            "review_count": 14000,
            "price_level": 2,
            "popularity_score": 83.0,
            "women_friendly": True,
        },
    ),
]

# 전체 동남아 시드
SOUTHEAST_ASIA_SEED = [
    *BANGKOK_SEED,
    *BALI_SEED,
    *SINGAPORE_SEED,
    *HANOI_SEED,
    *HOCHIMINH_SEED,
    *KUALA_LUMPUR_SEED,
]
