"""도쿄 큐레이션 시드 (30곳)."""
from .helpers import unsplash

TOKYO_SEED: list[tuple[str, dict]] = [
    # ── 카페 ──
    ("seed:tokyo:fuglen", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "푸글렌 도쿄", "name_en": "Fuglen Tokyo",
        "address": "1 Chome-16-11 Tomigaya, Shibuya City, Tokyo",
        "latitude": 35.6675, "longitude": 139.6857,
        "category": "cafe", "vibe_tags": ["빈티지", "감성", "조용"],
        "description": "노르웨이 오슬로 본점의 도쿄 분점. 빈티지 가구와 스페셜티 커피.",
        "cover_image": unsplash("photo-1559925393-8be0ec4767c8"),
        "instagram_hashtag": "#fuglentokyo", "rating": 4.5, "review_count": 1200,
        "price_level": 2, "popularity_score": 92.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:tokyo:streamer-coffee", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "스트리머 커피 컴퍼니", "name_en": "Streamer Coffee Company",
        "address": "1 Chome-20-28 Shibuya, Tokyo",
        "latitude": 35.6620, "longitude": 139.7016,
        "category": "cafe", "vibe_tags": ["모던", "감성", "활기"],
        "description": "라떼아트 챔피언이 운영하는 카페. 모던한 인테리어.",
        "cover_image": unsplash("photo-1495474472287-4d71bcdd2085"),
        "instagram_hashtag": "#streamercoffee", "rating": 4.4, "review_count": 980,
        "price_level": 2, "popularity_score": 85.0, "women_friendly": True,
    }),
    ("seed:tokyo:koffee-mameya", {
        "country": "JP", "city": "tokyo", "region": "오모테산도",
        "name": "코피 마메야", "name_en": "Koffee Mameya",
        "address": "4 Chome-15-3 Jingumae, Shibuya City, Tokyo",
        "latitude": 35.6685, "longitude": 139.7095,
        "category": "cafe", "vibe_tags": ["모던", "고급", "조용"],
        "description": "원두 전문점이자 컵 한 잔의 미니멀 카페. 바리스타가 취향을 묻고 추천.",
        "cover_image": unsplash("photo-1442512595331-e89e73853f31"),
        "instagram_hashtag": "#koffeemameya", "rating": 4.7, "review_count": 850,
        "price_level": 3, "popularity_score": 88.0,
    }),
    ("seed:tokyo:bluebottle-aoyama", {
        "country": "JP", "city": "tokyo", "region": "아오야마",
        "name": "블루보틀 아오야마", "name_en": "Blue Bottle Coffee Aoyama",
        "address": "3 Chome-13-14 Minamiaoyama, Minato City, Tokyo",
        "latitude": 35.6638, "longitude": 139.7197,
        "category": "cafe", "vibe_tags": ["모던", "조용"],
        "description": "샌프란시스코 본점 정신 그대로의 핸드드립 카페.",
        "cover_image": unsplash("photo-1509042239860-f550ce710b93"),
        "instagram_hashtag": "#bluebottlecoffee", "rating": 4.3, "review_count": 2100,
        "price_level": 2, "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:tokyo:omotesando-koffee", {
        "country": "JP", "city": "tokyo", "region": "오모테산도",
        "name": "오모테산도 커피", "name_en": "Omotesando Koffee",
        "address": "4 Chome-15-3 Jingumae, Shibuya City, Tokyo",
        "latitude": 35.6688, "longitude": 139.7098,
        "category": "cafe", "vibe_tags": ["감성", "고급"],
        "description": "큐브 모양 커스타드 푸딩과 에스프레소 명소.",
        "cover_image": unsplash("photo-1521017432531-fbd92d768814"),
        "instagram_hashtag": "#omotesandokoffee", "rating": 4.5, "review_count": 740,
        "price_level": 3, "popularity_score": 78.0,
    }),

    # ── 디저트 ──
    ("seed:tokyo:flippers", {
        "country": "JP", "city": "tokyo", "region": "시모키타자와",
        "name": "플리퍼스 시모키타자와", "name_en": "Flipper's Shimokitazawa",
        "address": "2 Chome-26-20 Kitazawa, Setagaya City, Tokyo",
        "latitude": 35.6614, "longitude": 139.6680,
        "category": "dessert", "vibe_tags": ["감성", "인스타", "활기"],
        "description": "기적의 팬케이크라 불리는 수플레 팬케이크.",
        "cover_image": unsplash("photo-1567620905732-2d1ec7ab7445"),
        "instagram_hashtag": "#flipperspancake", "rating": 4.3, "review_count": 1500,
        "price_level": 2, "popularity_score": 80.0, "women_friendly": True,
    }),
    ("seed:tokyo:harbs", {
        "country": "JP", "city": "tokyo", "region": "롯폰기",
        "name": "하브스 롯폰기힐스", "name_en": "Harbs Roppongi Hills",
        "address": "6 Chome-10-1 Roppongi, Minato City, Tokyo",
        "latitude": 35.6604, "longitude": 139.7292,
        "category": "dessert", "vibe_tags": ["고급", "분위기"],
        "description": "두꺼운 케이크 한 조각에 진심인 일본 케이크 체인.",
        "cover_image": unsplash("photo-1565958011703-44f9829ba187"),
        "instagram_hashtag": "#harbscake", "rating": 4.4, "review_count": 720,
        "price_level": 3, "popularity_score": 75.0, "women_friendly": True,
    }),
    ("seed:tokyo:dominique-ansel", {
        "country": "JP", "city": "tokyo", "region": "오모테산도",
        "name": "도미니크 앙셀 베이커리", "name_en": "Dominique Ansel Bakery",
        "address": "5 Chome-7-14 Jingumae, Shibuya City, Tokyo",
        "latitude": 35.6661, "longitude": 139.7090,
        "category": "dessert", "vibe_tags": ["감성", "인스타", "고급"],
        "description": "크로넛 창시자의 도쿄 매장. 줄 서서 먹는 디저트.",
        "cover_image": unsplash("photo-1488477181946-6428a0291777"),
        "instagram_hashtag": "#dominiqueanseltokyo", "rating": 4.4, "review_count": 1100,
        "price_level": 3, "popularity_score": 79.0, "women_friendly": True,
    }),
    ("seed:tokyo:gontran-cherrier", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "공트랑 셰리에", "name_en": "Gontran Cherrier",
        "address": "Shibuya Stream, 3-21-3 Shibuya, Tokyo",
        "latitude": 35.6571, "longitude": 139.7029,
        "category": "dessert", "vibe_tags": ["모던", "감성"],
        "description": "파리식 베이커리. 크루아상과 페이스트리.",
        "cover_image": unsplash("photo-1555507036-ab1f4038808a"),
        "instagram_hashtag": "#gontrancherrier", "rating": 4.3, "review_count": 480,
        "price_level": 2, "popularity_score": 70.0, "women_friendly": True,
    }),

    # ── 포토스팟 ──
    ("seed:tokyo:shibuya-crossing", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "시부야 스크램블 교차로", "name_en": "Shibuya Scramble Crossing",
        "address": "Shibuya City, Tokyo",
        "latitude": 35.6595, "longitude": 139.7005,
        "category": "photospot", "vibe_tags": ["야경", "활기", "인스타"],
        "description": "세계에서 가장 붐비는 교차로. SHIBUYA SKY에서 부감 사진.",
        "cover_image": unsplash("photo-1542051841857-5f90071e7989"),
        "instagram_hashtag": "#shibuyacrossing", "rating": 4.6, "review_count": 12000,
        "popularity_score": 98.0, "safety_score": 5,
    }),
    ("seed:tokyo:nakameguro-river", {
        "country": "JP", "city": "tokyo", "region": "나카메구로",
        "name": "나카메구로 메구로강", "name_en": "Meguro River",
        "address": "Nakameguro, Meguro City, Tokyo",
        "latitude": 35.6440, "longitude": 139.6986,
        "category": "photospot", "vibe_tags": ["감성", "한적", "분위기"],
        "description": "봄에는 벚꽃, 평소에는 한적한 산책로. 강변 카페와 어우러진다.",
        "cover_image": unsplash("photo-1522383225653-ed111181a951"),
        "instagram_hashtag": "#nakameguro", "rating": 4.6, "review_count": 3400,
        "popularity_score": 86.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:tokyo:teamlab-planets", {
        "country": "JP", "city": "tokyo", "region": "도요스",
        "name": "팀랩 플래닛 도쿄", "name_en": "teamLab Planets TOKYO",
        "address": "6-1-16 Toyosu, Koto City, Tokyo",
        "latitude": 35.6492, "longitude": 139.7913,
        "category": "photospot", "vibe_tags": ["인스타", "모던", "감성"],
        "description": "맨발로 물 위를 걷는 몰입형 디지털 아트 뮤지엄.",
        "cover_image": unsplash("photo-1551801841-ecad875a5142"),
        "instagram_hashtag": "#teamlabplanets", "rating": 4.7, "review_count": 9500,
        "price_level": 3, "popularity_score": 94.0, "women_friendly": True,
    }),
    ("seed:tokyo:senso-ji", {
        "country": "JP", "city": "tokyo", "region": "아사쿠사",
        "name": "센소지 절", "name_en": "Senso-ji Temple",
        "address": "2 Chome-3-1 Asakusa, Taito City, Tokyo",
        "latitude": 35.7148, "longitude": 139.7967,
        "category": "photospot", "vibe_tags": ["레트로", "분위기", "활기"],
        "description": "도쿄에서 가장 오래된 사찰. 카미나리몬 대형 등롱이 시그니처.",
        "cover_image": unsplash("photo-1583416750470-965b2707b355"),
        "instagram_hashtag": "#sensoji", "rating": 4.5, "review_count": 18000,
        "popularity_score": 95.0, "safety_score": 5,
    }),
    ("seed:tokyo:tokyo-tower", {
        "country": "JP", "city": "tokyo", "region": "미나토",
        "name": "도쿄 타워", "name_en": "Tokyo Tower",
        "address": "4 Chome-2-8 Shibakoen, Minato City, Tokyo",
        "latitude": 35.6586, "longitude": 139.7454,
        "category": "photospot", "vibe_tags": ["야경", "레트로", "분위기"],
        "description": "도쿄 스카이라인의 상징. 야간 점등 시 인생샷.",
        "cover_image": unsplash("photo-1536098561742-ca998e48cbcc"),
        "instagram_hashtag": "#tokyotower", "rating": 4.4, "review_count": 22000,
        "price_level": 2, "popularity_score": 90.0, "safety_score": 5,
    }),
    ("seed:tokyo:yanaka", {
        "country": "JP", "city": "tokyo", "region": "야나카",
        "name": "야나카 긴자 상점가", "name_en": "Yanaka Ginza",
        "address": "Yanaka, Taito City, Tokyo",
        "latitude": 35.7274, "longitude": 139.7660,
        "category": "photospot", "vibe_tags": ["레트로", "한적", "조용"],
        "description": "쇼와 시대 그대로 남은 골목길. 도쿄 속 시간 여행.",
        "cover_image": unsplash("photo-1554188248-986adbb73be4"),
        "instagram_hashtag": "#yanakaginza", "rating": 4.5, "review_count": 2800,
        "popularity_score": 73.0, "safety_score": 5,
    }),

    # ── 쇼핑 ──
    ("seed:tokyo:shimokitazawa", {
        "country": "JP", "city": "tokyo", "region": "시모키타자와",
        "name": "시모키타자와 빈티지 거리", "name_en": "Shimokitazawa Vintage Street",
        "address": "Kitazawa, Setagaya City, Tokyo",
        "latitude": 35.6614, "longitude": 139.6685,
        "category": "shopping", "vibe_tags": ["빈티지", "레트로", "활기"],
        "description": "빈티지 의류·중고 LP·소규모 카페가 모인 골목.",
        "cover_image": unsplash("photo-1604754742629-3e0498a8f4ee"),
        "instagram_hashtag": "#shimokitazawa", "rating": 4.5, "review_count": 4200,
        "popularity_score": 89.0, "tax_free": True,
    }),
    ("seed:tokyo:ginza-six", {
        "country": "JP", "city": "tokyo", "region": "긴자",
        "name": "긴자 식스", "name_en": "GINZA SIX",
        "address": "6 Chome-10-1 Ginza, Chuo City, Tokyo",
        "latitude": 35.6695, "longitude": 139.7644,
        "category": "shopping", "vibe_tags": ["고급", "모던"],
        "description": "긴자 최대 럭셔리 백화점. 면세·츠타야 서점 명소.",
        "cover_image": unsplash("photo-1567721913486-6585f069b332"),
        "instagram_hashtag": "#ginzasix", "rating": 4.4, "review_count": 5600,
        "price_level": 4, "popularity_score": 84.0, "tax_free": True, "safety_score": 5,
    }),
    ("seed:tokyo:harajuku-takeshita", {
        "country": "JP", "city": "tokyo", "region": "하라주쿠",
        "name": "하라주쿠 다케시타 거리", "name_en": "Takeshita Street",
        "address": "1 Chome Jingumae, Shibuya City, Tokyo",
        "latitude": 35.6713, "longitude": 139.7029,
        "category": "shopping", "vibe_tags": ["인스타", "활기", "레트로"],
        "description": "10대 패션·크레페·캐릭터샵의 성지.",
        "cover_image": unsplash("photo-1554188248-986adbb73be4"),
        "instagram_hashtag": "#takeshitastreet", "rating": 4.3, "review_count": 9800,
        "price_level": 2, "popularity_score": 87.0, "tax_free": True,
    }),
    ("seed:tokyo:don-quijote-shibuya", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "돈키호테 시부야점", "name_en": "Don Quijote Shibuya",
        "address": "1 Chome-23-15 Dogenzaka, Shibuya City, Tokyo",
        "latitude": 35.6585, "longitude": 139.6989,
        "category": "shopping", "vibe_tags": ["가성비", "활기"],
        "description": "24시간 만물상. 면세·기념품·간식의 보고.",
        "cover_image": unsplash("photo-1604719312566-8912e9227c6a"),
        "instagram_hashtag": "#donquijote", "rating": 4.2, "review_count": 7600,
        "price_level": 2, "popularity_score": 82.0, "tax_free": True,
    }),
    ("seed:tokyo:loft-shibuya", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "로프트 시부야", "name_en": "Loft Shibuya",
        "address": "21-1 Udagawacho, Shibuya City, Tokyo",
        "latitude": 35.6629, "longitude": 139.6987,
        "category": "shopping", "vibe_tags": ["모던", "감성"],
        "description": "일본 디자인 문구·라이프스타일 편집숍의 대표 매장.",
        "cover_image": unsplash("photo-1505740420928-5e560c06d30e"),
        "instagram_hashtag": "#loftjapan", "rating": 4.4, "review_count": 3400,
        "price_level": 2, "popularity_score": 76.0, "tax_free": True, "women_friendly": True,
    }),

    # ── 식당 ──
    ("seed:tokyo:ichiran-shibuya", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "이치란 시부야점", "name_en": "Ichiran Shibuya",
        "address": "1 Chome-22-7 Jinnan, Shibuya City, Tokyo",
        "latitude": 35.6612, "longitude": 139.6985,
        "category": "restaurant", "vibe_tags": ["조용", "가성비"],
        "description": "1인 칸막이 좌석으로 유명한 돈코츠 라멘 체인.",
        "cover_image": unsplash("photo-1569718212165-3a8278d5f624"),
        "instagram_hashtag": "#ichiran", "rating": 4.2, "review_count": 8400,
        "price_level": 2, "popularity_score": 83.0, "women_friendly": True, "solo_female_review_count": 120,
    }),
    ("seed:tokyo:afuri-harajuku", {
        "country": "JP", "city": "tokyo", "region": "하라주쿠",
        "name": "아후리 하라주쿠", "name_en": "AFURI Harajuku",
        "address": "3 Chome-63-1 Sendagaya, Shibuya City, Tokyo",
        "latitude": 35.6709, "longitude": 139.7027,
        "category": "restaurant", "vibe_tags": ["모던", "가성비"],
        "description": "유즈 향이 나는 깔끔한 시오 라멘. 여성 손님 비율 높음.",
        "cover_image": unsplash("photo-1623341214825-9f4f963727da"),
        "instagram_hashtag": "#afuri", "rating": 4.3, "review_count": 3200,
        "price_level": 2, "popularity_score": 78.0, "women_friendly": True,
    }),
    ("seed:tokyo:sushiro-shibuya", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "스시로 시부야점", "name_en": "Sushiro Shibuya",
        "address": "21-7 Udagawacho, Shibuya City, Tokyo",
        "latitude": 35.6634, "longitude": 139.6981,
        "category": "restaurant", "vibe_tags": ["가성비", "활기"],
        "description": "100엔 회전초밥 체인. 가성비 좋은 한 끼.",
        "cover_image": unsplash("photo-1579871494447-9811cf80d66c"),
        "instagram_hashtag": "#sushiro", "rating": 4.0, "review_count": 5400,
        "price_level": 1, "popularity_score": 74.0,
    }),
    ("seed:tokyo:gonpachi-nishiazabu", {
        "country": "JP", "city": "tokyo", "region": "니시아자부",
        "name": "곤파치 니시아자부", "name_en": "Gonpachi Nishiazabu",
        "address": "1 Chome-13-11 Nishiazabu, Minato City, Tokyo",
        "latitude": 35.6593, "longitude": 139.7264,
        "category": "restaurant", "vibe_tags": ["분위기", "고급", "분위기"],
        "description": "킬빌 촬영지로 알려진 일본식 이자카야.",
        "cover_image": unsplash("photo-1554118811-1e0d58224f24"),
        "instagram_hashtag": "#gonpachi", "rating": 4.3, "review_count": 2800,
        "price_level": 3, "popularity_score": 77.0,
    }),
    ("seed:tokyo:tsukemen-rokurinsha", {
        "country": "JP", "city": "tokyo", "region": "도쿄역",
        "name": "츠케멘 로쿠린샤", "name_en": "Rokurinsha Tokyo",
        "address": "1 Chome-9-1 Marunouchi, Chiyoda City, Tokyo",
        "latitude": 35.6812, "longitude": 139.7671,
        "category": "restaurant", "vibe_tags": ["가성비", "활기"],
        "description": "도쿄역 라멘 스트리트 대표 츠케멘.",
        "cover_image": unsplash("photo-1591814468924-caf88d1232e1"),
        "instagram_hashtag": "#rokurinsha", "rating": 4.4, "review_count": 4100,
        "price_level": 2, "popularity_score": 80.0,
    }),

    # ── 자연/문화 ──
    ("seed:tokyo:shinjuku-gyoen", {
        "country": "JP", "city": "tokyo", "region": "신주쿠",
        "name": "신주쿠 교엔", "name_en": "Shinjuku Gyoen National Garden",
        "address": "11 Naitomachi, Shinjuku City, Tokyo",
        "latitude": 35.6852, "longitude": 139.7100,
        "category": "nature", "vibe_tags": ["한적", "감성", "조용"],
        "description": "도심 속 거대 정원. 봄 벚꽃·가을 단풍 명소.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "instagram_hashtag": "#shinjukugyoen", "rating": 4.6, "review_count": 14000,
        "price_level": 1, "popularity_score": 88.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:tokyo:ueno-park", {
        "country": "JP", "city": "tokyo", "region": "우에노",
        "name": "우에노 공원", "name_en": "Ueno Park",
        "address": "Uenokoen, Taito City, Tokyo",
        "latitude": 35.7156, "longitude": 139.7745,
        "category": "nature", "vibe_tags": ["한적", "활기", "감성"],
        "description": "박물관·동물원·벚꽃이 모인 도쿄 대표 공원.",
        "cover_image": unsplash("photo-1490772888775-55fceea286b8"),
        "instagram_hashtag": "#uenopark", "rating": 4.5, "review_count": 9200,
        "popularity_score": 84.0, "safety_score": 5,
    }),
    ("seed:tokyo:meiji-jingu", {
        "country": "JP", "city": "tokyo", "region": "하라주쿠",
        "name": "메이지 신궁", "name_en": "Meiji Jingu",
        "address": "1-1 Yoyogikamizonocho, Shibuya City, Tokyo",
        "latitude": 35.6764, "longitude": 139.6993,
        "category": "culture", "vibe_tags": ["한적", "조용", "분위기"],
        "description": "도심 속 거대 숲 신사. 메이지 천황을 모신다.",
        "cover_image": unsplash("photo-1480796927426-f609979314bd"),
        "instagram_hashtag": "#meijijingu", "rating": 4.6, "review_count": 11000,
        "popularity_score": 87.0, "women_friendly": True, "safety_score": 5,
    }),

    # ── 바 ──
    ("seed:tokyo:bar-benfiddich", {
        "country": "JP", "city": "tokyo", "region": "니시신주쿠",
        "name": "바 벤피딕", "name_en": "Bar BenFiddich",
        "address": "1 Chome-13-7 Nishishinjuku, Shinjuku City, Tokyo",
        "latitude": 35.6907, "longitude": 139.6975,
        "category": "bar", "vibe_tags": ["분위기", "고급", "조용"],
        "description": "허브 칵테일로 유명한 세계 50대 바.",
        "cover_image": unsplash("photo-1514362545857-3bc16c4c7d1b"),
        "instagram_hashtag": "#barbenfiddich", "rating": 4.7, "review_count": 1200,
        "price_level": 4, "popularity_score": 76.0,
    }),
    ("seed:tokyo:nonbeiyokocho", {
        "country": "JP", "city": "tokyo", "region": "시부야",
        "name": "논베이 요코초", "name_en": "Nonbei Yokocho",
        "address": "1 Chome-25 Shibuya, Tokyo",
        "latitude": 35.6601, "longitude": 139.7027,
        "category": "bar", "vibe_tags": ["레트로", "분위기", "활기"],
        "description": "시부야 뒷골목 쇼와 시대 술집 거리.",
        "cover_image": unsplash("photo-1521017432531-fbd92d768814"),
        "instagram_hashtag": "#nonbeiyokocho", "rating": 4.3, "review_count": 2400,
        "price_level": 2, "popularity_score": 75.0,
    }),

    # ── 호텔 ──
    ("seed:tokyo:hoshinoya-tokyo", {
        "country": "JP", "city": "tokyo", "region": "오테마치",
        "name": "호시노야 도쿄", "name_en": "Hoshinoya Tokyo",
        "address": "1 Chome-9-1 Otemachi, Chiyoda City, Tokyo",
        "latitude": 35.6886, "longitude": 139.7670,
        "category": "hotel", "vibe_tags": ["고급", "조용", "분위기"],
        "description": "도심 속 료칸. 옥상 온천이 시그니처.",
        "cover_image": unsplash("photo-1566073771259-6a8506099945"),
        "instagram_hashtag": "#hoshinoyatokyo", "rating": 4.7, "review_count": 480,
        "price_level": 4, "popularity_score": 80.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:tokyo:park-hyatt-tokyo", {
        "country": "JP", "city": "tokyo", "region": "니시신주쿠",
        "name": "파크 하얏트 도쿄", "name_en": "Park Hyatt Tokyo",
        "address": "3-7-1-2 Nishishinjuku, Shinjuku City, Tokyo",
        "latitude": 35.6857, "longitude": 139.6914,
        "category": "hotel", "vibe_tags": ["고급", "야경", "모던"],
        "description": "영화 '사랑도 통역이 되나요' 배경. 뉴욕 바 야경 명소.",
        "cover_image": unsplash("photo-1455587734955-081b22074882"),
        "instagram_hashtag": "#parkhyatttokyo", "rating": 4.6, "review_count": 1900,
        "price_level": 4, "popularity_score": 82.0, "women_friendly": True, "safety_score": 5,
    }),
]
