"""여수 큐레이션 시드 (8곳)."""
from .helpers import unsplash

YEOSU_SEED: list[tuple[str, dict]] = [
    ("seed:yeosu:dolsan-bridge", {
        "country": "KR", "city": "yeosu", "region": "돌산",
        "name": "돌산대교 야경", "name_en": "Dolsan Bridge Night View",
        "address": "전라남도 여수시 돌산읍",
        "latitude": 34.7345, "longitude": 127.7418,
        "category": "photospot", "vibe_tags": ["야간", "바다", "감성"],
        "description": "여수 야경 1번지. 돌산대교 야간 조명과 바다 반영이 장관.",
        "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
        "rating": 4.6, "review_count": 12000, "price_level": 1,
        "popularity_score": 92.0, "women_friendly": True, "safety_score": 5,
    }),
    ("seed:yeosu:jinnamgwan", {
        "country": "KR", "city": "yeosu", "region": "군자동",
        "name": "진남관", "name_en": "Jinnamgwan",
        "address": "전라남도 여수시 동문로 11",
        "latitude": 34.7435, "longitude": 127.7368,
        "category": "culture", "vibe_tags": ["역사", "전통"],
        "description": "이순신 장군 전라좌수영 본영. 현존 최대 단층 목조건물 국보 324호.",
        "cover_image": unsplash("photo-1528360983277-13d401cdc186"),
        "rating": 4.3, "review_count": 6800, "price_level": 1,
        "popularity_score": 82.0, "women_friendly": True,
    }),
    ("seed:yeosu:yeosu-night-sea", {
        "country": "KR", "city": "yeosu", "region": "이순신광장",
        "name": "여수 이순신광장", "name_en": "Yeosu Yi Sun-sin Square",
        "address": "전라남도 여수시 이순신광장로 1",
        "latitude": 34.7453, "longitude": 127.7383,
        "category": "nature", "vibe_tags": ["바다", "활기", "야간"],
        "description": "오동도 입구 광장. 버스킹·포장마차·해산물 야시장. 낭만 여수의 중심.",
        "cover_image": unsplash("photo-1507525428034-b723cf961d3e"),
        "rating": 4.4, "review_count": 15000, "price_level": 1,
        "popularity_score": 90.0, "women_friendly": True,
    }),
    ("seed:yeosu:odongdo-island", {
        "country": "KR", "city": "yeosu", "region": "오동도",
        "name": "오동도", "name_en": "Odongdo Island",
        "address": "전라남도 여수시 오동도로 222",
        "latitude": 34.7398, "longitude": 127.7535,
        "category": "nature", "vibe_tags": ["자연", "힐링", "바다"],
        "description": "동백꽃 군락지. 방파제 산책로로 연결된 섬. 등대·용굴 트레킹.",
        "cover_image": unsplash("photo-1476820865390-c52aeebb9891"),
        "rating": 4.4, "review_count": 9500, "price_level": 1,
        "popularity_score": 86.0, "women_friendly": True,
    }),
    ("seed:yeosu:aqua-planet", {
        "country": "KR", "city": "yeosu", "region": "웅천동",
        "name": "여수 아쿠아플라넷", "name_en": "Yeosu Aqua Planet",
        "address": "전라남도 여수시 오동도로 61-11",
        "latitude": 34.7312, "longitude": 127.7455,
        "category": "culture", "vibe_tags": ["가족", "활기"],
        "description": "국내 최대 수족관. 벨루가·상어·가오리 등 280종. 2012 엑스포장 내.",
        "cover_image": unsplash("photo-1518020382113-a7e8fc38eac9"),
        "rating": 4.2, "review_count": 7200, "price_level": 3,
        "popularity_score": 80.0, "women_friendly": True,
    }),
    ("seed:yeosu:geobukseon-seafood", {
        "country": "KR", "city": "yeosu", "region": "교동",
        "name": "여수 돌게장 & 해산물", "name_en": "Yeosu Seafood Market",
        "address": "전라남도 여수시 교동",
        "latitude": 34.7445, "longitude": 127.7290,
        "category": "restaurant", "vibe_tags": ["맛집", "현지느낌"],
        "description": "여수 명물 갓김치·돌게장·서대회 무침. 재래시장 내 해산물 식당가.",
        "cover_image": unsplash("photo-1519984388953-d2406bc725e1"),
        "rating": 4.5, "review_count": 8900, "price_level": 2,
        "popularity_score": 88.0,
    }),
    ("seed:yeosu:maritime-cable-car", {
        "country": "KR", "city": "yeosu", "region": "돌산",
        "name": "여수 해상 케이블카", "name_en": "Yeosu Maritime Cable Car",
        "address": "전라남도 여수시 돌산읍 돌산로 3600",
        "latitude": 34.7280, "longitude": 127.7398,
        "category": "nature", "vibe_tags": ["바다뷰", "활기", "감성"],
        "description": "돌산과 자산공원을 잇는 해상 케이블카. 바닥 유리 곤돌라에서 바다 조망.",
        "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
        "rating": 4.5, "review_count": 11000, "price_level": 2,
        "popularity_score": 88.0, "women_friendly": True,
    }),
    ("seed:yeosu:hyangiram-hermitage", {
        "country": "KR", "city": "yeosu", "region": "돌산",
        "name": "향일암", "name_en": "Hyangiram Hermitage",
        "address": "전라남도 여수시 돌산읍 향일암로 60",
        "latitude": 34.6790, "longitude": 127.7895,
        "category": "culture", "vibe_tags": ["영적", "일출", "자연"],
        "description": "바위 절벽 위 암자. 한국 4대 관음기도처. 새해 일출 명소 1위.",
        "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
        "rating": 4.6, "review_count": 8500, "price_level": 1,
        "popularity_score": 84.0, "women_friendly": True,
    }),
]
