"""요코하마 큐레이션 시드 (10곳)."""

from .helpers import unsplash

YOKOHAMA_SEED: list[tuple[str, dict]] = [
    (
        "seed:yokohama:minato-mirai",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "니시구",
            "name": "미나토미라이21",
            "name_en": "Minato Mirai 21",
            "address": "Minato Mirai, Nishi Ward, Yokohama",
            "latitude": 35.4563,
            "longitude": 139.6313,
            "category": "photospot",
            "vibe_tags": ["모던", "야간", "활기"],
            "description": "요코하마 항구 재개발 지구. 랜드마크 타워·대관람차·야경이 한곳에.",
            "cover_image": unsplash("photo-1503899036084-c55cdd92da26"),
            "rating": 4.4,
            "review_count": 16000,
            "price_level": 2,
            "popularity_score": 92.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:yokohama:chinatown",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "나카구",
            "name": "요코하마 차이나타운",
            "name_en": "Yokohama Chinatown",
            "address": "Yamashitacho, Naka Ward, Yokohama",
            "latitude": 35.4434,
            "longitude": 139.6509,
            "category": "restaurant",
            "vibe_tags": ["맛집", "활기", "현지느낌"],
            "description": "일본 최대 차이나타운. 600개 이상 중화요리·잡화점. 고기만두·탕수육.",
            "cover_image": unsplash("photo-1555396273-367ea4eb4db5"),
            "rating": 4.2,
            "review_count": 21000,
            "price_level": 2,
            "popularity_score": 90.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:yokohama:yamashita-park",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "나카구",
            "name": "야마시타 공원",
            "name_en": "Yamashita Park",
            "address": "279 Yamashitacho, Naka Ward, Yokohama",
            "latitude": 35.4445,
            "longitude": 139.6522,
            "category": "nature",
            "vibe_tags": ["힐링", "자연", "바다"],
            "description": "요코하마 항구를 따라 이어지는 해안 공원. 히카와마루 선박 정박.",
            "cover_image": unsplash("photo-1532274402911-5a369e4c4bb5"),
            "rating": 4.3,
            "review_count": 8700,
            "price_level": 1,
            "popularity_score": 83.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:yokohama:sankeien-garden",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "나카구",
            "name": "산케이엔 정원",
            "name_en": "Sankeien Garden",
            "address": "58-1 Honmoku Sannotani, Naka Ward, Yokohama",
            "latitude": 35.4218,
            "longitude": 139.6517,
            "category": "nature",
            "vibe_tags": ["자연", "전통", "조용"],
            "description": "메이지 시대 실업가 조성 정원. 일본 전통 가옥·탑·연못이 어우러짐.",
            "cover_image": unsplash("photo-1476820865390-c52aeebb9891"),
            "rating": 4.5,
            "review_count": 5200,
            "price_level": 2,
            "popularity_score": 79.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:yokohama:cup-noodles-museum",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "니시구",
            "name": "컵누들 뮤지엄 요코하마",
            "name_en": "Cup Noodles Museum Yokohama",
            "address": "2-3-4 Shinko, Nishi Ward, Yokohama",
            "latitude": 35.4572,
            "longitude": 139.6428,
            "category": "culture",
            "vibe_tags": ["활기", "가족"],
            "description": "컵라면 발명가 안도 모모후쿠의 박물관. 나만의 컵라면 만들기 체험.",
            "cover_image": unsplash("photo-1518020382113-a7e8fc38eac9"),
            "rating": 4.3,
            "review_count": 9800,
            "price_level": 2,
            "popularity_score": 85.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:yokohama:red-brick-warehouse",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "나카구",
            "name": "요코하마 붉은 벽돌창고",
            "name_en": "Yokohama Red Brick Warehouse",
            "address": "1-1 Shinko, Naka Ward, Yokohama",
            "latitude": 35.4543,
            "longitude": 139.6418,
            "category": "shopping",
            "vibe_tags": ["빈티지", "감성", "활기"],
            "description": "메이지~다이쇼 시대 세관 창고 리모델링. 레스토랑·잡화·이벤트 공간.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.2,
            "review_count": 13500,
            "price_level": 2,
            "popularity_score": 88.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:yokohama:yokohama-museum-art",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "니시구",
            "name": "요코하마 미술관",
            "name_en": "Yokohama Museum of Art",
            "address": "3-4-1 Minatomirai, Nishi Ward, Yokohama",
            "latitude": 35.4547,
            "longitude": 139.6295,
            "category": "culture",
            "vibe_tags": ["예술", "조용", "모던"],
            "description": "일본 근현대 미술 명품 컬렉션. 피카소·달리 등 서양 현대 미술도 소장.",
            "cover_image": unsplash("photo-1518998053901-5348d3961a04"),
            "rating": 4.3,
            "review_count": 4100,
            "price_level": 2,
            "popularity_score": 74.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:yokohama:yokohama-ramen-museum",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "신요코하마",
            "name": "신요코하마 라면 박물관",
            "name_en": "Shin-Yokohama Ramen Museum",
            "address": "2-14-21 Shinyokohama, Kohoku Ward, Yokohama",
            "latitude": 35.5090,
            "longitude": 139.6173,
            "category": "restaurant",
            "vibe_tags": ["맛집", "현지느낌", "활기"],
            "description": "쇼와 33년 거리를 재현한 레트로 공간. 일본 각 지역 명물 라면 9종.",
            "cover_image": unsplash("photo-1569718212165-3a8278d5f624"),
            "rating": 4.3,
            "review_count": 8500,
            "price_level": 2,
            "popularity_score": 83.0,
        },
    ),
    (
        "seed:yokohama:motomachi-street",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "나카구",
            "name": "모토마치 쇼핑 거리",
            "name_en": "Motomachi Shopping Street",
            "address": "Motomachi, Naka Ward, Yokohama",
            "latitude": 35.4402,
            "longitude": 139.6492,
            "category": "shopping",
            "vibe_tags": ["고급", "감성", "트렌디"],
            "description": "요코하마 원조 세련된 쇼핑 거리. 유럽풍 건물에 로컬 패션·잡화.",
            "cover_image": unsplash("photo-1555529669-e69e7aa0ba9a"),
            "rating": 4.1,
            "review_count": 5900,
            "price_level": 3,
            "popularity_score": 76.0,
            "women_friendly": True,
        },
    ),
    (
        "seed:yokohama:landmark-tower-sky-garden",
        {
            "country": "JP",
            "city": "yokohama",
            "region": "니시구",
            "name": "랜드마크 타워 스카이가든",
            "name_en": "Landmark Tower Sky Garden",
            "address": "2-2-1 Minatomirai, Nishi Ward, Yokohama",
            "latitude": 35.4560,
            "longitude": 139.6307,
            "category": "photospot",
            "vibe_tags": ["뷰포인트", "야간", "모던"],
            "description": "69층 270m 전망대. 요코하마·도쿄만 360도 파노라마. 야경 최고.",
            "cover_image": unsplash("photo-1506905925346-21bda4d32df4"),
            "rating": 4.4,
            "review_count": 12000,
            "price_level": 2,
            "popularity_score": 87.0,
            "women_friendly": True,
        },
    ),
]
