"""add_expo_push_token_to_users

Revision ID: 1a24eb872fa6
Revises: accce84b59d8
Create Date: 2026-05-16 00:31:07.816856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a24eb872fa6"
down_revision: Union[str, Sequence[str], None] = "accce84b59d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("expo_push_token", sa.String(length=200), nullable=True))
    op.create_index(op.f("ix_users_expo_push_token"), "users", ["expo_push_token"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_expo_push_token"), table_name="users")
    op.drop_column("users", "expo_push_token")
    # ### end Alembic commands ###
