"""add_destination_to_trips

Revision ID: 364386175efc
Revises: 1a24eb872fa6
Create Date: 2026-05-16 17:00:59.602197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "364386175efc"
down_revision: Union[str, Sequence[str], None] = "1a24eb872fa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("destination", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "destination")
    # ### end Alembic commands ###
