"""convert_images_to_jsonb

Revision ID: 6ae1afe5b308
Revises: ad1a0564de1e
Create Date: 2026-05-16 17:22:55.980111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ae1afe5b308"
down_revision: Union[str, Sequence[str], None] = "ad1a0564de1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NULLIF 처리: 빈 문자열이 있을 경우 NULL로 변환 후 jsonb 캐스팅
    op.execute(
        "ALTER TABLE locations ALTER COLUMN images TYPE JSONB USING NULLIF(images, '')::jsonb"
    )
    op.execute(
        "ALTER TABLE saved_places ALTER COLUMN images TYPE JSONB USING NULLIF(images, '')::jsonb"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "saved_places",
        "images",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "locations",
        "images",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
