"""add_share_token_expires_at

Revision ID: accce84b59d8
Revises: b6ea4133a1ce
Create Date: 2026-05-15 17:50:27.942351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "accce84b59d8"
down_revision: Union[str, Sequence[str], None] = "b6ea4133a1ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trips", sa.Column("share_token_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "share_token_expires_at")
    # ### end Alembic commands ###
