"""add saved_places checklist location_fields trip_fields

Revision ID: b6ea4133a1ce
Revises: 9e9b7e787198
Create Date: 2026-05-15 08:03:32.993252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6ea4133a1ce"
down_revision: Union[str, Sequence[str], None] = "9e9b7e787198"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checklist_items",
        "category",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'짐'::text"),
    )
    op.alter_column(
        "checklist_items",
        "text",
        existing_type=sa.TEXT(),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_checklist_trip"), table_name="checklist_items")
    op.alter_column(
        "locations",
        "phone",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "locations",
        "website",
        existing_type=sa.TEXT(),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "locations", "rating", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
    )
    op.alter_column(
        "locations",
        "google_place_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_locations_trip_id"), table_name="locations")
    op.alter_column(
        "saved_places",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_places",
        "address",
        existing_type=sa.TEXT(),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_places",
        "latitude",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_places",
        "longitude",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_places",
        "category",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'관광지'::text"),
    )
    op.alter_column(
        "saved_places",
        "google_place_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "saved_places", "rating", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
    )
    op.alter_column(
        "saved_places",
        "website",
        existing_type=sa.TEXT(),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "saved_places",
        "phone",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_saved_places_user"), table_name="saved_places")
    op.alter_column(
        "trips",
        "share_token",
        existing_type=sa.TEXT(),
        type_=sa.String(length=64),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_trips_user_id"), table_name="trips")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_trips_user_id"), "trips", ["user_id"], unique=False)
    op.alter_column(
        "trips",
        "share_token",
        existing_type=sa.String(length=64),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_index(op.f("idx_saved_places_user"), "saved_places", ["user_id"], unique=False)
    op.alter_column(
        "saved_places",
        "phone",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "saved_places",
        "website",
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "saved_places", "rating", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "saved_places",
        "google_place_id",
        existing_type=sa.String(length=200),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "saved_places",
        "category",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'관광지'::text"),
    )
    op.alter_column(
        "saved_places",
        "longitude",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_places",
        "latitude",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_places",
        "address",
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_places",
        "name",
        existing_type=sa.String(length=200),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_locations_trip_id"), "locations", ["trip_id"], unique=False)
    op.alter_column(
        "locations",
        "google_place_id",
        existing_type=sa.String(length=200),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "locations", "rating", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "locations",
        "website",
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "locations",
        "phone",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_index(op.f("idx_checklist_trip"), "checklist_items", ["trip_id"], unique=False)
    op.alter_column(
        "checklist_items",
        "text",
        existing_type=sa.String(length=300),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "checklist_items",
        "category",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'짐'::text"),
    )
    # ### end Alembic commands ###
